	.align 2
gCryTable:: @ 869DCF4
	@ Gen 1
	cry Cry_Meadosaur  @ 869DCF4
	cry Cry_Grovine  @ 869DD00
	cry Cry_Yggdracon  @ 869DD0C
	cry Cry_Skorchi  @ 869DD18
	cry Cry_Skomad  @ 869DD24
	cry Cry_Skorpyros  @ 869DD30
	cry Cry_Jissm  @ 869DD3C
	cry Cry_Splooger  @ 869DD48
	cry Cry_Speriathon  @ 869DD54
	cry Cry_Bug  @ 869DD60
	cry Cry_Legoog  @ 869DD6C
	cry Cry_Firome  @ 869DD78
	cry Cry_Paintic  @ 869DD84
	cry Cry_Myresft  @ 869DD90
	cry Cry_Berrord  @ 869DD9C
	cry Cry_Emelgy  @ 869DDA8
	cry Cry_Fedorhawk  @ 869DDB4
	cry Cry_Fazeagle  @ 869DDC0
	cry Cry_Hangster  @ 869DDCC
	cry Cry_Gawdamster  @ 869DDD8
	cry Cry_Birdapp  @ 869DDE4
	cry Cry_Chapsnat  @ 869DDF0
	cry Cry_Alcoo  @ 869DDFC
	cry Cry_Bevragon  @ 869DE08
	cry Cry_Skippa  @ 869DE14
	cry Cry_Disheats  @ 869DE20
	cry Cry_Jafeet  @ 869DE2C
	cry Cry_Toyuta  @ 869DE38
	cry Cry_Nauseon  @ 869DE44
	cry Cry_Hazmate  @ 869DE50
	cry Cry_Ebolable  @ 869DE5C
	cry Cry_Unga  @ 869DE68
	cry Cry_Bunga  @ 869DE74
	cry Cry_Oogabooga  @ 869DE80
	cry Cry_Egoirl  @ 869DE8C
	cry Cry_Gothot  @ 869DE98
	cry Cry_Saucie  @ 869DEA4
	cry Cry_Sawsbaws  @ 869DEB0
	cry Cry_Sneddit  @ 869DEBC
	cry Cry_Cosmie  @ 869DEC8
	cry Cry_Batanarf  @ 869DED4
	cry Cry_Anivenom  @ 869DEE0
	cry Cry_Bongstard  @ 869DEEC
	cry Cry_Smogas  @ 869DEF8
	cry Cry_Ganjaze  @ 869DF04
	cry Cry_Goofshrum  @ 869DF10
	cry Cry_Dushroom  @ 869DF1C
	cry Cry_Araketsu  @ 869DF28
	cry Cry_Senketula  @ 869DF34
	cry Cry_Diglett  @ 869DF40
	cry Cry_Ghoma  @ 869DF4C
	cry Cry_Garfel  @ 869DF58
	cry Cry_Gorefield  @ 869DF64
	cry Cry_Duggame  @ 869DF70
	cry Cry_Perripus  @ 869DF7C
	cry Cry_Aganda  @ 869DF88
	cry Cry_Sugreivous  @ 869DF94
	cry Cry_Ctheye  @ 869DFA0
	cry Cry_Opticulu  @ 869DFAC
	cry Cry_Ootlaw  @ 869DFB8
	cry Cry_Sherrif  @ 869DFC4
	cry Cry_Renagede  @ 869DFD0
	cry Cry_Kuklux  @ 869DFDC
	cry Cry_Kuklan  @ 869DFE8
	cry Cry_Kuklops  @ 869DFF4
	cry Cry_Farby  @ 869E000
	cry Cry_Furbois  @ 869E00C
	cry Cry_Longifer  @ 869E018
	cry Cry_Bongecko  @ 869E024
	cry Cry_Mariguana  @ 869E030
	cry Cry_Marleyzard  @ 869E03C
	cry Cry_Flootey  @ 869E048
	cry Cry_Freddifer  @ 869E054
	cry Cry_Rock  @ 869E060
	cry Cry_Toncrete  @ 869E06C
	cry Cry_Lossilith  @ 869E078
	cry Cry_Debeguck  @ 869E084
	cry Cry_Lonky  @ 869E090
	cry Cry_Basshop  @ 869E09C
	cry Cry_Shemue  @ 869E0A8
	cry Cry_Desquared  @ 869E0B4
	cry Cry_Deathcubed  @ 869E0C0
	cry Cry_Impostown  @ 869E0CC
	cry Cry_Divini  @ 869E0D8
	cry Cry_Parangelia  @ 869E0E4
	cry Cry_Dabboi  @ 869E0F0
	cry Cry_Titenic  @ 869E0FC
	cry Cry_Gummi  @ 869E108
	cry Cry_Muk  @ 869E114
	cry Cry_Coolar  @ 869E120
	cry Cry_Fridege  @ 869E12C
	cry Cry_Skeledoot  @ 869E138
	cry Cry_Beegmike  @ 869E144
	cry Cry_Sans  @ 869E150
	cry Cry_Esceepee  @ 869E15C
	cry Cry_Shapipiz  @ 869E168
	cry Cry_Shapoopyz  @ 869E174
	cry Cry_Stroloke  @ 869E180
	cry Cry_Creepa  @ 869E18C
	cry Cry_Awmane  @ 869E198
	cry Cry_Endermon  @ 869E1A4
	cry Cry_Billominat  @ 869E1B0
	cry Cry_Ciphron  @ 869E1BC
	cry Cry_Surbsquach  @ 869E1C8
	cry Cry_Amazulk  @ 869E1D4
	cry Cry_Replitor  @ 869E1E0
	cry Cry_Biremic  @ 869E1EC
	cry Cry_Capfalco  @ 869E1F8
	cry Cry_Fennaf  @ 869E204
	cry Cry_Bipharma  @ 869E210
	cry Cry_Potogreed  @ 869E21C
	cry Cry_Yeesaur  @ 869E228
	cry Cry_Unjoy  @ 869E234
	cry Cry_Bananace  @ 869E240
	cry Cry_Trololo  @ 869E24C
	cry Cry_Jank  @ 869E258
	cry Cry_Swampogre  @ 869E264
	cry Cry_Cighted  @ 869E270
	cry Cry_Mongelord  @ 869E27C
	cry Cry_Burik  @ 869E288
	cry Cry_Bicyelion  @ 869E294
	cry Cry_Alien  @ 869E2A0
	cry Cry_Chuxkush  @ 869E2AC
	cry Cry_Repsac  @ 869E2B8
	cry Cry_Krafpunk  @ 869E2C4
	cry Cry_Endmysuff  @ 869E2D0
	cry Cry_Itrimid  @ 869E2DC
	cry Cry_Grox  @ 869E2E8
	cry Cry_Nushake  @ 869E2F4
	cry Cry_Kroller  @ 869E300
	cry Cry_Jebony  @ 869E30C
	cry Cry_Ditto  @ 869E318
	cry Cry_Eemojee  @ 869E324
	cry Cry_Stresseon  @ 869E330
	cry Cry_Xokkeon  @ 869E33C
	cry Cry_Babeyon  @ 869E348
	cry Cry_Auricliary  @ 869E354
	cry Cry_Attaco  @ 869E360
	cry Cry_Gaiser  @ 869E36C
	cry Cry_Corork  @ 869E378
	cry Cry_Bigobeet  @ 869E384
	cry Cry_Usarmy  @ 869E390
	cry Cry_Shepeird  @ 869E39C
	cry Cry_Legend  @ 869E3A8
	cry Cry_Zeruel  @ 869E3B4
	cry Cry_Remiel  @ 869E3C0
	cry Cry_Amonsus  @ 869E3CC
	cry Cry_Wooptret  @ 869E3D8
	cry Cry_Killworu  @ 869E3E4
	cry Cry_God  @ 869E3F0
	cry Cry_Thevoid  @ 869E3FC
	@ Gen 2
	cry Cry_Tom  @ 869E408
	cry Cry_Zactory  @ 869E414
	cry Cry_Rammet  @ 869E420
	cry Cry_Megatron  @ 869E42C
	cry Cry_Rigamort  @ 869E438
	cry Cry_Rickle  @ 869E444
	cry Cry_Korbie  @ 869E450
	cry Cry_Jewis  @ 869E45C
	cry Cry_Teed  @ 869E468
	cry Cry_Goncariciv  @ 869E474
	cry Cry_Deepfrieon  @ 869E480
	cry Cry_WormadamT  @ 869E48C
	cry Cry_Jadoug  @ 869E498
	cry Cry_Abominaton  @ 869E4A4
	cry Cry_Wurm  @ 869E4B0
	cry Cry_Phracer  @ 869E4BC
	cry Cry_Gluerilla  @ 869E4C8
	cry Cry_Luis  @ 869E4D4
	cry Cry_Lovlilad  @ 869E4E0
	cry Cry_Ourobolet  @ 869E4EC
	cry Cry_Pichu  @ 869E4F8
	cry Cry_Pooprat  @ 869E504
	cry Cry_Vcrbrain  @ 869E510
	cry Cry_Filmbrain  @ 869E51C
	cry Cry_Blurabrain  @ 869E528
	cry Cry_Puckid  @ 869E534
	cry Cry_Goalem  @ 869E540
	cry Cry_Baddery  @ 869E54C
	cry Cry_Durashell  @ 869E558
	cry Cry_Bacid  @ 869E564
	cry Cry_Seawee  @ 869E570
	cry Cry_Seakush  @ 869E57C
	cry Cry_Barireefer  @ 869E588
	cry Cry_Breaddie  @ 869E594
	cry Cry_Toastem  @ 869E5A0
	cry Cry_Dogeaster  @ 869E5AC
	cry Cry_Anoobis  @ 869E5B8
	cry Cry_Nightwave  @ 869E5C4
	cry Cry_Charles  @ 869E5D0
	cry Cry_Melarick  @ 869E5DC
	cry Cry_Wreckfast  @ 869E5E8
	cry Cry_Sharcrush  @ 869E5F4
	cry Cry_Megaladeth  @ 869E600
	cry Cry_Arealgun  @ 869E60C
	cry Cry_Dont  @ 869E618
	cry Cry_Leave  @ 869E624
	cry Cry_Gahblin  @ 869E630
	cry Cry_Gooblan  @ 869E63C
	cry Cry_Lilreaper  @ 869E648
	cry Cry_Unown  @ 869E654
	cry Cry_Firant  @ 869E660
	cry Cry_Burnant  @ 869E66C
	cry Cry_Antinder  @ 869E678
	cry Cry_Waile  @ 869E684
	cry Cry_Moaby  @ 869E690
	cry Cry_Shawt  @ 869E69C
	cry Cry_Holocast  @ 869E6A8
	cry Cry_Grubdab  @ 869E6B4
	cry Cry_Dabbug  @ 869E6C0
	cry Cry_Dabbeatle  @ 869E6CC
	cry Cry_Nuggie  @ 869E6D8
	cry Cry_Mcchicky  @ 869E6E4
	cry Cry_Happymaul  @ 869E6F0
	cry Cry_Pinati  @ 869E6FC
	cry Cry_Vivapinaut  @ 869E708
	cry Cry_Maurrice  @ 869E714
	cry Cry_Slugma  @ 869E720
	cry Cry_Sugmaballs  @ 869E72C
	cry Cry_Orcale  @ 869E738
	cry Cry_Scrapchat  @ 869E744
	cry Cry_Setronic  @ 869E750
	cry Cry_Bannaconda  @ 869E75C
	cry Cry_Systanic  @ 869E768
	cry Cry_Abstratic  @ 869E774
	cry Cry_Flooticorn  @ 869E780
	cry Cry_Legearth  @ 869E78C
	cry Cry_Leguessr  @ 869E798
	cry Cry_Minimal  @ 869E7A4
	cry Cry_Dismalo  @ 869E7B0
	cry Cry_Mortarmalo  @ 869E7BC
	cry Cry_Cofficrab  @ 869E7C8
	cry Cry_Craberave  @ 869E7D4
	cry Cry_Gnorb  @ 869E7E0
	cry Cry_Gahnomed  @ 869E7EC
	cry Cry_Drywee  @ 869E7F8
	cry Cry_Straidirt  @ 869E804
	cry Cry_Burntonion  @ 869E810
	cry Cry_Platerry  @ 869E81C
	cry Cry_Rickling  @ 869E828
	cry Cry_Pants  @ 869E834
	cry Cry_Reapcharge  @ 869E840
	cry Cry_Shockitty  @ 869E84C
	cry Cry_Heattar  @ 869E858
	cry Cry_Reingeer  @ 869E864
	cry Cry_Frosling  @ 869E870
	cry Cry_Froshund  @ 869E87C
	cry Cry_Frosilisk  @ 869E888
	cry Cry_Helpme  @ 869E894
	cry Cry_Suffer  @ 869E8A0
	cry Cry_Lilguy  @ 869E8AC
	@ Gen 3
	cry Cry_Berryalen
	cry Cry_Veryberry
	cry Cry_Incredalen
	cry Cry_Cooklet
	cry Cry_Chefure
	cry Cry_Gourmaster
	cry Cry_Baitord
	cry Cry_Baiterror
	cry Cry_Baitank
	cry Cry_Duplicat
	cry Cry_Furrlead
	cry Cry_Meowrrior
	cry Cry_Zeppur
	cry Cry_Zepurrine
	cry Cry_Nyankitty
	cry Cry_Nyantiger
	cry Cry_Mechduck
	cry Cry_Duckertron
	cry Cry_Scubite
	cry Cry_Quackshot
	cry Cry_Quacknator
	cry Cry_Sobbleaf
	cry Cry_Herokku
	cry Cry_Shadeku
	cry Cry_Taillow
	cry Cry_Xapp
	cry Cry_Batcardi
	cry Cry_Noctrum
	cry Cry_Notafurry
	cry Cry_Sortafurry
	cry Cry_Thatsfurry
	cry Cry_Whiskball
	cry Cry_Cinamancer
	cry Cry_Blinky
	cry Cry_Doublinker
	cry Cry_Doobob
	cry Cry_Doodoobob
	cry Cry_Ugadooba
	cry Cry_Nincada
	cry Cry_Ninjask
	cry Cry_Shedinja
	cry Cry_Cowerlin
	cry Cry_Bravogor
	cry Cry_Gigalpha
	cry Cry_Angbeast
	cry Cry_Gangbeats
	cry Cry_Azurill
	cry Cry_Scatrush
	cry Cry_Smoslime
	cry Cry_Nyancat
	cry Cry_Secritler
	cry Cry_Minitron
	cry Cry_Aron
	cry Cry_Galvatron
	cry Cry_Murphire
	cry Cry_Lonk
	cry Cry_Lonkest
	cry Cry_Cordra
	cry Cry_Auxilisk
	cry Cry_Purrsour
	cry Cry_Purrtang
	cry Cry_Rewindle
	cry Cry_Dndice
	cry Cry_Alieon
	cry Cry_Symbite
	cry Cry_Carnigore
	cry Cry_Brewfin
	cry Cry_Sharkeg
	cry Cry_Shrimpot
	cry Cry_Lobscald
	cry Cry_Vulpointer
	cry Cry_Errorine
	cry Cry_Hellaphant
	cry Cry_Fizzcub
	cry Cry_Seltclaw
	cry Cry_Yeltzer
	cry Cry_Metiore
	cry Cry_Cometide
	cry Cry_Galadrake
	cry Cry_Yolkanner
	cry Cry_Aconeggs
	cry Cry_Armydrone
	cry Cry_UNSC
	cry Cry_Smitnion
	cry Cry_Arackne
	cry Cry_Surtyur
	cry Cry_Ganesh
	cry Cry_Coopid
	cry Cry_Splashicoot
	cry Cry_Nongetive
	cry Cry_Nononmon
	cry Cry_Dreidrill
	cry Cry_Heburrow
	cry Cry_Odosaur
	cry Cry_Pyrabass
	cry Cry_Triceras
	cry Cry_Xenotops
	cry Cry_Paddlite
	cry Cry_Nutvalanche
	cry Cry_Castform
	cry Cry_Kecleon
	cry Cry_Ticktowel
	cry Cry_Tocktower
	cry Cry_Ratman
	cry Cry_Hugeman
	cry Cry_Tropius
	cry Cry_Kirbairde
	cry Cry_Fredbar
	cry Cry_Babinion
	cry Cry_Chairold
	cry Cry_Elechair
	cry Cry_Piraghoul
	cry Cry_Morghost
	cry Cry_Phasmorgan
	cry Cry_Golbnar
	cry Cry_Globnaut
	cry Cry_Thaumnar
	cry Cry_Galacnar
	cry Cry_Warpnar
	cry Cry_Sipking
	cry Cry_Tipsyramid
	cry Cry_Drunkabus
	cry Cry_Yelleye
	cry Cry_Harastur
	cry Cry_Hazethoth
	cry Cry_Regirock
	cry Cry_Regice
	cry Cry_Nawffle
	cry Cry_Latias
	cry Cry_Latios
	cry Cry_Krakrum
	cry Cry_Noirnet
	cry Cry_Rayquaza
	cry Cry_Thiscraker
	cry Cry_Deoxys
	@ Gen 4
	cry_not Cry_Turtwig
	cry_not Cry_Grotle
	cry_not Cry_Torterra
	cry_not Cry_Embob
	cry_not Cry_Coalgar
	cry_not Cry_Bobistic
	cry_not Cry_Oroflow
	cry_not Cry_Orocast
	cry_not Cry_Orrowhelm
	cry_not Cry_Starly
	cry_not Cry_Staravia
	cry_not Cry_Staraptor
	cry_not Cry_Xdik
	cry_not Cry_Xdemon
	cry_not Cry_Desitrus
	cry_not Cry_Desqueeze
	cry_not Cry_Shinx
	cry_not Cry_Luxio
	cry_not Cry_Luxray
	cry_not Cry_Banslip
	cry_not Cry_Roserade
	cry_not Cry_Cranidos
	cry_not Cry_Rampardos
	cry_not Cry_Shieldon
	cry_not Cry_Bastiodon
	cry_not Cry_Parslito
	cry_not Cry_Mojisley
	cry_not Cry_Gailord
	cry_not Cry_Combee
	cry_not Cry_Vespiquen
	cry_not Cry_Pachirisu
	cry_not Cry_Squigga
	cry_not Cry_Desparward
	cry_not Cry_Bushizard
	cry_not Cry_Notyuhdad
	cry_not Cry_Choccudle
	cry_not Cry_Choctic
	cry_not Cry_Ambipom
	cry_not Cry_Drifloon
	cry_not Cry_Drifblim
	cry_not Cry_Buneary
	cry_not Cry_Lopunny
	cry_not Cry_Mismagius
	cry_not Cry_Honchkrow
	cry_not Cry_Glameow
	cry_not Cry_Gorfold
	cry_not Cry_Luiwee
	cry_not Cry_Stunky
	cry_not Cry_Skuntank
	cry_not Cry_Bronzor
	cry_not Cry_Bronzong
	cry_not Cry_Bonsly
	cry_not Cry_Mimejr
	cry_not Cry_Hangingy
	cry_not Cry_Enderagon
	cry_not Cry_Chancer
	cry_not Cry_Capple
	cry_not Cry_Shellhaul
	cry_not Cry_Truckoise
	cry_not Cry_Trololing
	cry_not Cry_Brixel
	cry_not Cry_Bloknock
	cry_not Cry_Journemap
	cry_not Cry_Journeship
	cry_not Cry_Skorupi
	cry_not Cry_Drapion
	cry_not Cry_Croagunk
	cry_not Cry_Toxicroak
	cry_not Cry_Carnivine
	cry_not Cry_Finneon
	cry_not Cry_Lumineon
	cry_not Cry_Mantyke
	cry_not Cry_Snover
	cry_not Cry_Abomasnow
	cry_not Cry_Fredunkle
	cry_not Cry_Magnezone
	cry_not Cry_Lickilicky
	cry_not Cry_Rhyperior
	cry_not Cry_Tangrowth
	cry_not Cry_Electivire
	cry_not Cry_Toastrider
	cry_not Cry_Togekiss
	cry_not Cry_Yanmega
	cry_not Cry_Leafeon
	cry_not Cry_Glaceon
	cry_not Cry_Gliscor
	cry_not Cry_Mamoswine
	cry_not Cry_Hellspack
	cry_not Cry_Gallade
	cry_not Cry_Probopass
	cry_not Cry_Skeledoom
	cry_not Cry_Blinkrupt
	cry_not Cry_Rotom
	cry_not Cry_Uxie
	cry_not Cry_Mesprit
	cry_not Cry_Azelf
	cry_not Cry_Dialga
	cry_not Cry_Palkia
	cry_not Cry_Heatran
	cry_not Cry_Regigigas
	cry_not Cry_Giratina
	cry_not Cry_Cresselia
	cry_not Cry_Phione
	cry_not Cry_Manaphy
	cry_not Cry_Darkrai
	cry_not Cry_Shaymin
	cry_not Cry_Arceus
	@ Gen 5
	cry_not Cry_Victini
	cry_not Cry_Snivy
	cry_not Cry_Servine
	cry_not Cry_Serperior
	cry_not Cry_Tepig
	cry_not Cry_Pignite
	cry_not Cry_Emboar
	cry_not Cry_Oshawott
	cry_not Cry_Dewott
	cry_not Cry_Samurott
	cry_not Cry_Patrat
	cry_not Cry_Watchog
	cry_not Cry_Lillipup
	cry_not Cry_Herdier
	cry_not Cry_Stoutland
	cry_not Cry_Purrloin
	cry_not Cry_Liepard
	cry_not Cry_Pansage
	cry_not Cry_Simisage
	cry_not Cry_Pansear
	cry_not Cry_Simisear
	cry_not Cry_Panpour
	cry_not Cry_Simipour
	cry_not Cry_Munna
	cry_not Cry_Musharna
	cry_not Cry_Pidove
	cry_not Cry_Tranquill
	cry_not Cry_Unfezant
	cry_not Cry_Blitzle
	cry_not Cry_Zebstrika
	cry_not Cry_Roggenrola
	cry_not Cry_Boldore
	cry_not Cry_Gigalith
	cry_not Cry_Woobat
	cry_not Cry_Swoobat
	cry_not Cry_Drilbur
	cry_not Cry_Excadrill
	cry_not Cry_Audino
	cry_not Cry_Timburr
	cry_not Cry_Gurdurr
	cry_not Cry_Conkeldurr
	cry_not Cry_Tympole
	cry_not Cry_Palpitoad
	cry_not Cry_Seismitoad
	cry_not Cry_Throh
	cry_not Cry_Sawk
	cry_not Cry_Sewaddle
	cry_not Cry_Swadloon
	cry_not Cry_Leavanny
	cry_not Cry_Venipede
	cry_not Cry_Whirlipede
	cry_not Cry_Scolipede
	cry_not Cry_Cottonee
	cry_not Cry_Whimsicott
	cry_not Cry_Petilil
	cry_not Cry_Lilligant
	cry_not Cry_Basculin
	cry_not Cry_Sandile
	cry_not Cry_Krokorok
	cry_not Cry_Krookodile
	cry_not Cry_Darumaka
	cry_not Cry_Darmanitan
	cry_not Cry_Maractus
	cry_not Cry_Dwebble
	cry_not Cry_Crustle
	cry_not Cry_Scraggy
	cry_not Cry_Scrafty
	cry_not Cry_Sigilyph
	cry_not Cry_Yamask
	cry_not Cry_Cofagrigus
	cry_not Cry_Tirtouga
	cry_not Cry_Carracosta
	cry_not Cry_Archen
	cry_not Cry_Archeops
	cry_not Cry_Trubbish
	cry_not Cry_Garbodor
	cry_not Cry_Zorua
	cry_not Cry_Zoroark
	cry_not Cry_Minccino
	cry_not Cry_Cinccino
	cry_not Cry_Gothita
	cry_not Cry_Gothorita
	cry_not Cry_Gothitelle
	cry_not Cry_Solosis
	cry_not Cry_Duosion
	cry_not Cry_Reuniclus
	cry_not Cry_Ducklett
	cry_not Cry_Swanna
	cry_not Cry_Vanillite
	cry_not Cry_Vanillish
	cry_not Cry_Vanilluxe
	cry_not Cry_Deerling
	cry_not Cry_Sawsbuck
	cry_not Cry_Emolga
	cry_not Cry_Karrablast
	cry_not Cry_Escavalier
	cry_not Cry_Foongus
	cry_not Cry_Amoonguss
	cry_not Cry_Frillish
	cry_not Cry_Jellicent
	cry_not Cry_Alomomola
	cry_not Cry_Joltik
	cry_not Cry_Galvantula
	cry_not Cry_Ferroseed
	cry_not Cry_Ferrothorn
	cry_not Cry_Klink
	cry_not Cry_Klang
	cry_not Cry_Klinklang
	cry_not Cry_Tynamo
	cry_not Cry_Eelektrik
	cry_not Cry_Eelektross
	cry_not Cry_Elgyem
	cry_not Cry_Beheeyem
	cry_not Cry_Litwick
	cry_not Cry_Lampent
	cry_not Cry_Chandelure
	cry_not Cry_Axew
	cry_not Cry_Fraxure
	cry_not Cry_Haxorus
	cry_not Cry_Cubchoo
	cry_not Cry_Beartic
	cry_not Cry_Cryogonal
	cry_not Cry_Shelmet
	cry_not Cry_Accelgor
	cry_not Cry_Stunfisk
	cry_not Cry_Mienfoo
	cry_not Cry_Mienshao
	cry_not Cry_Druddigon
	cry_not Cry_Golett
	cry_not Cry_Golurk
	cry_not Cry_Pawniard
	cry_not Cry_Bisharp
	cry_not Cry_Bouffalant
	cry_not Cry_Rufflet
	cry_not Cry_Braviary
	cry_not Cry_Vullaby
	cry_not Cry_Mandibuzz
	cry_not Cry_Heatmor
	cry_not Cry_Durant
	cry_not Cry_Deino
	cry_not Cry_Zweilous
	cry_not Cry_Hydreigon
	cry_not Cry_Larvesta
	cry_not Cry_Volcarona
	cry_not Cry_Cobalion
	cry_not Cry_Terrakion
	cry_not Cry_Virizion
	cry_not Cry_Tornadus
	cry_not Cry_Thundurus
	cry_not Cry_Reshiram
	cry_not Cry_Zekrom
	cry_not Cry_Landorus
	cry_not Cry_Kyurem
	cry_not Cry_Keldeo
	cry_not Cry_Meloetta
	cry_not Cry_Genesect
	@ Gen 6
	cry_not Cry_Chespin
	cry_not Cry_Quilladin
	cry_not Cry_Chesnaught
	cry_not Cry_Fennekin
	cry_not Cry_Braixen
	cry_not Cry_Delphox
	cry_not Cry_Froakie
	cry_not Cry_Frogadier
	cry_not Cry_Greninja
	cry_not Cry_Bunnelby
	cry_not Cry_Diggersby
	cry_not Cry_Fletchling
	cry_not Cry_Fletchinder
	cry_not Cry_Talonflame
	cry_not Cry_Scatterbug
	cry_not Cry_Spewpa
	cry_not Cry_Vivillon
	cry_not Cry_Litleo
	cry_not Cry_Pyroar
	cry_not Cry_Flabebe
	cry_not Cry_Floette
	cry_not Cry_Florges
	cry_not Cry_Skiddo
	cry_not Cry_Gogoat
	cry_not Cry_Pancham
	cry_not Cry_Pangoro
	cry_not Cry_Furfrou
	cry_not Cry_Espurr
	cry_not Cry_Meowstic
	cry_not Cry_Honedge
	cry_not Cry_Doublade
	cry_not Cry_Aegislash
	cry_not Cry_Spritzee
	cry_not Cry_Aromatisse
	cry_not Cry_Swirlix
	cry_not Cry_Slurpuff
	cry_not Cry_Inkay
	cry_not Cry_Malamar
	cry_not Cry_Binacle
	cry_not Cry_Barbaracle
	cry_not Cry_Skrelp
	cry_not Cry_Dragalge
	cry_not Cry_Clauncher
	cry_not Cry_Clawitzer
	cry_not Cry_Helioptile
	cry_not Cry_Heliolisk
	cry_not Cry_Tyrunt
	cry_not Cry_Tyrantrum
	cry_not Cry_Amaura
	cry_not Cry_Aurorus
	cry_not Cry_Sylveon
	cry_not Cry_Hawlucha
	cry_not Cry_Dedenne
	cry_not Cry_Carbink
	cry_not Cry_Goomy
	cry_not Cry_Sliggoo
	cry_not Cry_Goodra
	cry_not Cry_Klefki
	cry_not Cry_Phantump
	cry_not Cry_Trevenant
	cry_not Cry_Pumpkaboo
	cry_not Cry_Gourgeist
	cry_not Cry_Bergmite
	cry_not Cry_Avalugg
	cry_not Cry_Noibat
	cry_not Cry_Noivern
	cry_not Cry_Xerneas
	cry_not Cry_Yveltal
	cry_not Cry_Zygarde
	cry_not Cry_Diancie
	cry_not Cry_Hoopa
	cry_not Cry_Volcanion
	@ Gen 7
	cry_not Cry_Rowlet
	cry_not Cry_Dartrix
	cry_not Cry_Decidueye
	cry_not Cry_Litten
	cry_not Cry_Torracat
	cry_not Cry_Incineroar
	cry_not Cry_Popplio
	cry_not Cry_Brionne
	cry_not Cry_Primarina
	cry_not Cry_Pikipek
	cry_not Cry_Trumbeak
	cry_not Cry_Toucannon
	cry_not Cry_Yungoos
	cry_not Cry_Gumshoos
	cry_not Cry_Grubbin
	cry_not Cry_Charjabug
	cry_not Cry_Vikavolt
	cry_not Cry_Crabrawler
	cry_not Cry_Crabominable
	cry_not Cry_Oricorio
	cry_not Cry_Cutiefly
	cry_not Cry_Ribombee
	cry_not Cry_Rockruff
	cry_not Cry_Lycanroc
	cry_not Cry_Wishiwashi
	cry_not Cry_Mareanie
	cry_not Cry_Toxapex
	cry_not Cry_Mudbray
	cry_not Cry_Mudsdale
	cry_not Cry_Dewpider
	cry_not Cry_Araquanid
	cry_not Cry_Fomantis
	cry_not Cry_Lurantis
	cry_not Cry_Morelull
	cry_not Cry_Shiinotic
	cry_not Cry_Salandit
	cry_not Cry_Salazzle
	cry_not Cry_Stufful
	cry_not Cry_Bewear
	cry_not Cry_Bounsweet
	cry_not Cry_Steenee
	cry_not Cry_Tsareena
	cry_not Cry_Comfey
	cry_not Cry_Oranguru
	cry_not Cry_Passimian
	cry_not Cry_Wimpod
	cry_not Cry_Golisopod
	cry_not Cry_Sandygast
	cry_not Cry_Palossand
	cry_not Cry_Pyukumuku
	cry_not Cry_Type_null
	cry_not Cry_Silvally
	cry_not Cry_Minior
	cry_not Cry_Komala
	cry_not Cry_Turtonator
	cry_not Cry_Togedemaru
	cry_not Cry_Mimikyu
	cry_not Cry_Bruxish
	cry_not Cry_Drampa
	cry_not Cry_Dhelmise
	cry_not Cry_Jangmo_o
	cry_not Cry_Hakamo_o
	cry_not Cry_Kommo_o
	cry_not Cry_Tapu_koko
	cry_not Cry_Tapu_lele
	cry_not Cry_Tapu_bulu
	cry_not Cry_Tapu_fini
	cry_not Cry_Cosmog
	cry_not Cry_Cosmoem
	cry_not Cry_Solgaleo
	cry_not Cry_Lunala
	cry_not Cry_Nihilego
	cry_not Cry_Buzzwole
	cry_not Cry_Pheromosa
	cry_not Cry_Xurkitree
	cry_not Cry_Celesteela
	cry_not Cry_Kartana
	cry_not Cry_Guzzlord
	cry_not Cry_Necrozma
	cry_not Cry_Magearna
	cry_not Cry_Marshadow
	cry_not Cry_Poipole
	cry_not Cry_Naganadel
	cry_not Cry_Stakataka
	cry_not Cry_Blacephalon
	cry_not Cry_Zeraora
	cry_not Cry_Meltan
	cry_not Cry_Melmetal
	cry_not Cry_Grookey
	cry_not Cry_Thwackey
	cry_not Cry_Rillaboom
	cry_not Cry_Scorbunny
	cry_not Cry_Raboot
	cry_not Cry_Cinderace
	cry_not Cry_Sobble
	cry_not Cry_Drizzile
	cry_not Cry_Inteleon
	cry_not Cry_Skwovet
	cry_not Cry_Greedent
	cry_not Cry_Rookidee
	cry_not Cry_Corvisquire
	cry_not Cry_Corviknight
	cry_not Cry_Blipbug
	cry_not Cry_Dottler
	cry_not Cry_Orbeetle
	cry_not Cry_Nickit
	cry_not Cry_Thievul
	cry_not Cry_Gossifleur
	cry_not Cry_Eldegoss
	cry_not Cry_Wooloo
	cry_not Cry_Dubwool
	cry_not Cry_Chewtle
	cry_not Cry_Drednaw
	cry_not Cry_Yamper
	cry_not Cry_Boltund
	cry_not Cry_Rolycoly
	cry_not Cry_Carkol
	cry_not Cry_Coalossal
	cry_not Cry_Applin
	cry_not Cry_Flapple
	cry_not Cry_Appletun
	cry_not Cry_Silicobra
	cry_not Cry_Sandaconda
	cry_not Cry_Cramorant
	cry_not Cry_Arrokuda
	cry_not Cry_Barraskewda
	cry_not Cry_Toxel
	cry_not Cry_Toxtricity
	cry_not Cry_Sizzlipede
	cry_not Cry_Centiskorch
	cry_not Cry_Clobbopus
	cry_not Cry_Grapploct
	cry_not Cry_Sinistea
	cry_not Cry_Polteageist
	cry_not Cry_Hatenna
	cry_not Cry_Hattrem
	cry_not Cry_Hatterene
	cry_not Cry_Impidimp
	cry_not Cry_Morgrem
	cry_not Cry_Grimmsnarl
	cry_not Cry_Obstagoon
	cry_not Cry_Perrserker
	cry_not Cry_Cursola
	cry_not Cry_Sirfetchd
	cry_not Cry_MrRime
	cry_not Cry_Runerigus
	cry_not Cry_Milcery
	cry_not Cry_Alcremie
	cry_not Cry_Falinks
	cry_not Cry_Pincurchin
	cry_not Cry_Snom
	cry_not Cry_Frosmoth
	cry_not Cry_Stonjourner
	cry_not Cry_Eiscue
	cry_not Cry_Indeedee
	cry_not Cry_Morpeko
	cry_not Cry_Cufant
	cry_not Cry_Copperajah
	cry_not Cry_Dracozolt
	cry_not Cry_Arctozolt
	cry_not Cry_Dracovish
	cry_not Cry_Arctovish
	cry_not Cry_Duraludon
	cry_not Cry_Dreepy
	cry_not Cry_Drakloak
	cry_not Cry_Dragapult
	cry_not Cry_Zacian
	cry_not Cry_Zamazenta
	cry_not Cry_Eternatus
	cry_not Cry_Kubfu
	cry_not Cry_Urshifu
	cry_not Cry_Zarude
	cry_not Cry_Regieleki
	cry_not Cry_Regidrago
	cry_not Cry_Glastrier
	cry_not Cry_Spectrier
	cry_not Cry_Calyrex
	@ Megas
	cry_not Cry_Yggdracon_Mega
	cry_not Cry_Skorpyros_Mega_X
	cry_not Cry_Skorpyros_Mega_Y
	cry_not Cry_Speriathon_Mega
	cry_not Cry_BIPHARMA_MEGA
	cry_not Cry_Bug_Mega
	cry_not Cry_Gothot_Mega
	cry_not Cry_Dushroom_Mega
	cry_not Cry_Jank_Mega
	cry_not Cry_Rock_Mega
	cry_not Cry_Shepeird_Mega
	cry_not Cry_Sneddit_Mega
	cry_not Cry_Tom_Mega
	cry_not Cry_God_Mega_X
	cry_not Cry_God_Mega_Y
	cry_not Cry_Thevoid_Mega
	cry_not Cry_Gigalpha_Mega
	cry_not Cry_Gahnomed_Mega
	cry_not Cry_Goalem_Mega
	cry_not Cry_Incredalen_Mega
	cry_not Cry_Gourmaster_Mega
	cry_not Cry_Baitank_Mega
	cry_not Cry_Awmane_Mega
	cry_not Cry_Secritler_Mega
	cry_not Cry_Minitron_Mega
	cry_not Cry_Murphire_Mega
	cry_not Cry_Lonkest_Mega
	cry_not Cry_Auxilisk_Mega
	cry_not Cry_Sharkeg_Mega
	cry_not Cry_Errorine_Mega
	cry_not Cry_UNSC_Mega
	cry_not Cry_Tocktower_Mega
	cry_not Cry_Fredbar_Mega
	cry_not Cry_Elechair_Mega
	cry_not Cry_Drunkabus_Mega
	cry_not Cry_Hazethoth_Mega
	cry_not Cry_Latias_Mega
	cry_not Cry_Latios_Mega
	cry_not Cry_Lopunny_Mega
	cry_not Cry_Truckoise_Mega
	cry_not Cry_Bloknock_Mega
	cry_not Cry_Abomasnow_Mega
	cry_not Cry_Gallade_Mega
	cry_not Cry_UNJOY_MEGA
	cry_not Cry_Diancie_Mega
	@ Special Mega + Primals
	cry_not Cry_Rayquaza_Mega
	cry_not Cry_Krakrum_Primal
	cry_not Cry_Noirnet_Primal
	@ Alolan Forms
	cry Cry_Hangster
	cry Cry_Gawdamster
	cry Cry_Disheats
	cry Cry_Jafeet
	cry Cry_Toyuta
	cry Cry_Saucie
	cry Cry_Sawsbaws
	cry Cry_Diglett
	cry Cry_Ghoma
	cry Cry_Garfel
	cry Cry_Gorefield
	cry Cry_Rock
	cry Cry_Toncrete
	cry Cry_Lossilith
	cry Cry_Gummi
	cry Cry_Muk
	cry Cry_Ciphron
	cry Cry_Amazulk
	@ Galarian Forms
	cry Cry_Garfel
	cry Cry_Debeguck
	cry Cry_Lonky
	cry_not Cry_Basshop_Galarian
	cry Cry_Shemue
	cry Cry_Impostown
	cry Cry_Bipharma
	cry Cry_Alien
	cry Cry_Legend
	cry Cry_Zeruel
	cry Cry_Remiel
	cry Cry_Gooblan
	cry Cry_Setronic
	cry Cry_Meowrrior
	cry Cry_Zeppur
	cry_not Cry_Darumaka
	cry_not Cry_Darmanitan
	cry_not Cry_Yamask
	cry_not Cry_Stunfisk
	@ Misc Forms
	@ Cosplay Skippa
	cry Cry_Skippa  @ 869DE14
	cry Cry_Skippa  @ 869DE14
	cry Cry_Skippa  @ 869DE14
	cry Cry_Skippa  @ 869DE14
	cry Cry_Skippa  @ 869DE14
	cry Cry_Skippa  @ 869DE14
	@ Cap Skippa
	cry Cry_Skippa  @ 869DE14
	cry Cry_Skippa  @ 869DE14
	cry Cry_Skippa  @ 869DE14
	cry Cry_Skippa  @ 869DE14
	cry Cry_Skippa  @ 869DE14
	cry Cry_Skippa  @ 869DE14
	cry Cry_Skippa  @ 869DE14
	cry Cry_Skippa  @ 869DE14
	@ Pichu
	cry Cry_Pichu  @ 869E4F8
	@ Unown
	cry Cry_Unown  @ 869E654
	cry Cry_Unown  @ 869E654
	cry Cry_Unown  @ 869E654
	cry Cry_Unown  @ 869E654
	cry Cry_Unown  @ 869E654
	cry Cry_Unown  @ 869E654
	cry Cry_Unown  @ 869E654
	cry Cry_Unown  @ 869E654
	cry Cry_Unown  @ 869E654
	cry Cry_Unown  @ 869E654
	cry Cry_Unown  @ 869E654
	cry Cry_Unown  @ 869E654
	cry Cry_Unown  @ 869E654
	cry Cry_Unown  @ 869E654
	cry Cry_Unown  @ 869E654
	cry Cry_Unown  @ 869E654
	cry Cry_Unown  @ 869E654
	cry Cry_Unown  @ 869E654
	cry Cry_Unown  @ 869E654
	cry Cry_Unown  @ 869E654
	cry Cry_Unown  @ 869E654
	cry Cry_Unown  @ 869E654
	cry Cry_Unown  @ 869E654
	cry Cry_Unown  @ 869E654
	cry Cry_Unown  @ 869E654
	cry Cry_Unown  @ 869E654
	cry Cry_Unown  @ 869E654
	@ Castform
	cry Cry_Castform
	cry Cry_Castform
	cry Cry_Castform
	@ Deoxys
	cry Cry_Deoxys
	cry Cry_Deoxys
	cry Cry_Deoxys
	@ Parslito
	cry_not Cry_Parslito
	cry_not Cry_Parslito
	@ Mojisley
	cry_not Cry_Mojisley
	cry_not Cry_Mojisley
	@ Notyuhdad
	cry_not Cry_Notyuhdad
	@ Choccudle
	cry_not Cry_Choccudle
	@ Choctic
	cry_not Cry_Choctic
	@ Rotom
	cry_not Cry_Rotom
	cry_not Cry_Rotom
	cry_not Cry_Rotom
	cry_not Cry_Rotom
	cry_not Cry_Rotom
	@ Giratina
	cry_not Cry_Giratina
	@ Shaymin
	cry_not Cry_Shaymin_Sky
	@ Arceus
	cry_not Cry_Arceus
	cry_not Cry_Arceus
	cry_not Cry_Arceus
	cry_not Cry_Arceus
	cry_not Cry_Arceus
	cry_not Cry_Arceus
	cry_not Cry_Arceus
	cry_not Cry_Arceus
	cry_not Cry_Arceus
	cry_not Cry_Arceus
	cry_not Cry_Arceus
	cry_not Cry_Arceus
	cry_not Cry_Arceus
	cry_not Cry_Arceus
	cry_not Cry_Arceus
	cry_not Cry_Arceus
	cry_not Cry_Arceus
	@ Basculin
	cry_not Cry_Basculin
	@ Darmanitan
	cry_not Cry_Darmanitan
	cry_not Cry_Darmanitan
	@ Deerling
	cry_not Cry_Deerling
	cry_not Cry_Deerling
	cry_not Cry_Deerling
	@ Sawsbuck
	cry_not Cry_Sawsbuck
	cry_not Cry_Sawsbuck
	cry_not Cry_Sawsbuck
	@ Therian Forms
	cry_not Cry_Tornadus_Therian
	cry_not Cry_Thundurus_Therian
	cry_not Cry_Landorus_Therian
	@ Kyurem
	cry_not Cry_Kyurem_White
	cry_not Cry_Kyurem_Black
	@ Keldeo
	cry_not Cry_Keldeo
	@ Meloetta
	cry_not Cry_Meloetta
	@ Genesect
	cry_not Cry_Genesect
	cry_not Cry_Genesect
	cry_not Cry_Genesect
	cry_not Cry_Genesect
	@ Greninja
	cry_not Cry_Greninja
	cry_not Cry_Greninja
	@ Vivillon
	cry_not Cry_Vivillon
	cry_not Cry_Vivillon
	cry_not Cry_Vivillon
	cry_not Cry_Vivillon
	cry_not Cry_Vivillon
	cry_not Cry_Vivillon
	cry_not Cry_Vivillon
	cry_not Cry_Vivillon
	cry_not Cry_Vivillon
	cry_not Cry_Vivillon
	cry_not Cry_Vivillon
	cry_not Cry_Vivillon
	cry_not Cry_Vivillon
	cry_not Cry_Vivillon
	cry_not Cry_Vivillon
	cry_not Cry_Vivillon
	cry_not Cry_Vivillon
	cry_not Cry_Vivillon
	cry_not Cry_Vivillon
	@ Flabébé
	cry_not Cry_Flabebe
	cry_not Cry_Flabebe
	cry_not Cry_Flabebe
	cry_not Cry_Flabebe
	@ Floette
	cry_not Cry_Floette
	cry_not Cry_Floette
	cry_not Cry_Floette
	cry_not Cry_Floette
	cry_not Cry_Floette_Eternal_Flower
	@ Florges
	cry_not Cry_Florges
	cry_not Cry_Florges
	cry_not Cry_Florges
	cry_not Cry_Florges
	@ Furfrou
	cry_not Cry_Furfrou
	cry_not Cry_Furfrou
	cry_not Cry_Furfrou
	cry_not Cry_Furfrou
	cry_not Cry_Furfrou
	cry_not Cry_Furfrou
	cry_not Cry_Furfrou
	cry_not Cry_Furfrou
	cry_not Cry_Furfrou
	@ Meowstic
	cry_not Cry_Meowstic
	@ Aegislash
	cry_not Cry_Aegislash
	@ Pumpkaboo
	cry_not Cry_Pumpkaboo
	cry_not Cry_Pumpkaboo
	cry_not Cry_Pumpkaboo_Super
	@ Gourgeist
	cry_not Cry_Gourgeist
	cry_not Cry_Gourgeist
	cry_not Cry_Gourgeist_Super
	@ Xerneas
	cry_not Cry_Xerneas
	@ Zygarde
	cry_not Cry_Zygarde_10
	cry_not Cry_Zygarde_10
	cry_not Cry_Zygarde
	cry_not Cry_Zygarde_Complete
	@ Hoopa
	cry_not Cry_Hoopa_Unbound
	@ Oricorio
	cry_not Cry_Oricorio_Pom_Pom
	cry_not Cry_Oricorio_Pa_u
	cry_not Cry_Oricorio_Sensu
	@ Rockruff
	cry_not Cry_Rockruff
	@ Lycanroc
	cry_not Cry_Lycanroc_Midnight
	cry_not Cry_Lycanroc_Dusk
	@ Wishiwashi
	cry_not Cry_Wishiwashi_School
	@ Silvally
	cry_not Cry_Silvally
	cry_not Cry_Silvally
	cry_not Cry_Silvally
	cry_not Cry_Silvally
	cry_not Cry_Silvally
	cry_not Cry_Silvally
	cry_not Cry_Silvally
	cry_not Cry_Silvally
	cry_not Cry_Silvally
	cry_not Cry_Silvally
	cry_not Cry_Silvally
	cry_not Cry_Silvally
	cry_not Cry_Silvally
	cry_not Cry_Silvally
	cry_not Cry_Silvally
	cry_not Cry_Silvally
	cry_not Cry_Silvally
	@ Minior
	cry_not Cry_Minior
	cry_not Cry_Minior
	cry_not Cry_Minior
	cry_not Cry_Minior
	cry_not Cry_Minior
	cry_not Cry_Minior
	cry_not Cry_Minior
	cry_not Cry_Minior
	cry_not Cry_Minior
	cry_not Cry_Minior
	cry_not Cry_Minior
	cry_not Cry_Minior
	cry_not Cry_Minior
	@ Mimikyu
	cry_not Cry_Mimikyu
	@ Necrozma
	cry_not Cry_Necrozma_Dusk_Mane
	cry_not Cry_Necrozma_Dawn_Wings
	cry_not Cry_Necrozma_Ultra
	@ Magearna
	cry_not Cry_Magearna
	@ Cramorant
	cry_not Cry_Cramorant
	cry_not Cry_Cramorant
	@ Toxtricity
	cry_not Cry_Toxtricity_Low_Key
	@ Sinistea
	cry_not Cry_Sinistea
	@ Polteageist
	cry_not Cry_Polteageist
	@ Alcremie
	cry_not Cry_Alcremie
	cry_not Cry_Alcremie
	cry_not Cry_Alcremie
	cry_not Cry_Alcremie
	cry_not Cry_Alcremie
	cry_not Cry_Alcremie
	cry_not Cry_Alcremie
	cry_not Cry_Alcremie
	@ Eiscue
	cry_not Cry_Eiscue_Noice_Face
	@ Indeedee
	cry_not Cry_Indeedee_Female
	@ Morpeko
	cry_not Cry_Morpeko_Hangry
	@ Zacian
	cry_not Cry_Zacian_Crowned_Sword
	@ Zamazenta
	cry_not Cry_Zamazenta_Crowned_Shield
	@ Eternatus
	cry_not Cry_Eternatus_Eternamax
	@ Urshifu
	cry_not Cry_Urshifu_Rapid_Strike_Style
	@ Zarude
	cry_not Cry_Zarude
	@ Calyrex
	cry_not Cry_Calyrex_Ice_Rider
	cry_not Cry_Calyrex_Shadow_Rider

	.align 2
gCryTable2:: @ 869EF24
	cry2 Cry_Meadosaur  @ 869EF24
	cry2 Cry_Grovine  @ 869EF30
	cry2 Cry_Yggdracon  @ 869EF3C
	cry2 Cry_Skorchi  @ 869EF48
	cry2 Cry_Skomad  @ 869EF54
	cry2 Cry_Skorpyros  @ 869EF60
	cry2 Cry_Jissm  @ 869EF6C
	cry2 Cry_Splooger  @ 869EF78
	cry2 Cry_Speriathon  @ 869EF84
	cry2 Cry_Bug  @ 869EF90
	cry2 Cry_Legoog  @ 869EF9C
	cry2 Cry_Firome  @ 869EFA8
	cry2 Cry_Paintic  @ 869EFB4
	cry2 Cry_Myresft  @ 869EFC0
	cry2 Cry_Berrord  @ 869EFCC
	cry2 Cry_Emelgy  @ 869EFD8
	cry2 Cry_Fedorhawk  @ 869EFE4
	cry2 Cry_Fazeagle  @ 869EFF0
	cry2 Cry_Hangster  @ 869EFFC
	cry2 Cry_Gawdamster  @ 869F008
	cry2 Cry_Birdapp  @ 869F014
	cry2 Cry_Chapsnat  @ 869F020
	cry2 Cry_Alcoo  @ 869F02C
	cry2 Cry_Bevragon  @ 869F038
	cry2 Cry_Skippa  @ 869F044
	cry2 Cry_Disheats  @ 869F050
	cry2 Cry_Jafeet  @ 869F05C
	cry2 Cry_Toyuta  @ 869F068
	cry2 Cry_Nauseon  @ 869F074
	cry2 Cry_Hazmate  @ 869F080
	cry2 Cry_Ebolable  @ 869F08C
	cry2 Cry_Unga  @ 869F098
	cry2 Cry_Bunga  @ 869F0A4
	cry2 Cry_Oogabooga  @ 869F0B0
	cry2 Cry_Egoirl  @ 869F0BC
	cry2 Cry_Gothot  @ 869F0C8
	cry2 Cry_Saucie  @ 869F0D4
	cry2 Cry_Sawsbaws  @ 869F0E0
	cry2 Cry_Sneddit  @ 869F0EC
	cry2 Cry_Cosmie  @ 869F0F8
	cry2 Cry_Batanarf  @ 869F104
	cry2 Cry_Anivenom  @ 869F110
	cry2 Cry_Bongstard  @ 869F11C
	cry2 Cry_Smogas  @ 869F128
	cry2 Cry_Ganjaze  @ 869F134
	cry2 Cry_Goofshrum  @ 869F140
	cry2 Cry_Dushroom  @ 869F14C
	cry2 Cry_Araketsu  @ 869F158
	cry2 Cry_Senketula  @ 869F164
	cry2 Cry_Diglett  @ 869F170
	cry2 Cry_Ghoma  @ 869F17C
	cry2 Cry_Garfel  @ 869F188
	cry2 Cry_Gorefield  @ 869F194
	cry2 Cry_Duggame  @ 869F1A0
	cry2 Cry_Perripus  @ 869F1AC
	cry2 Cry_Aganda  @ 869F1B8
	cry2 Cry_Sugreivous  @ 869F1C4
	cry2 Cry_Ctheye  @ 869F1D0
	cry2 Cry_Opticulu  @ 869F1DC
	cry2 Cry_Ootlaw  @ 869F1E8
	cry2 Cry_Sherrif  @ 869F1F4
	cry2 Cry_Renagede  @ 869F200
	cry2 Cry_Kuklux  @ 869F20C
	cry2 Cry_Kuklan  @ 869F218
	cry2 Cry_Kuklops  @ 869F224
	cry2 Cry_Farby  @ 869F230
	cry2 Cry_Furbois  @ 869F23C
	cry2 Cry_Longifer  @ 869F248
	cry2 Cry_Bongecko  @ 869F254
	cry2 Cry_Mariguana  @ 869F260
	cry2 Cry_Marleyzard  @ 869F26C
	cry2 Cry_Flootey  @ 869F278
	cry2 Cry_Freddifer  @ 869F284
	cry2 Cry_Rock  @ 869F290
	cry2 Cry_Toncrete  @ 869F29C
	cry2 Cry_Lossilith  @ 869F2A8
	cry2 Cry_Debeguck  @ 869F2B4
	cry2 Cry_Lonky  @ 869F2C0
	cry2 Cry_Basshop  @ 869F2CC
	cry2 Cry_Shemue  @ 869F2D8
	cry2 Cry_Desquared  @ 869F2E4
	cry2 Cry_Deathcubed  @ 869F2F0
	cry2 Cry_Impostown  @ 869F2FC
	cry2 Cry_Divini  @ 869F308
	cry2 Cry_Parangelia  @ 869F314
	cry2 Cry_Dabboi  @ 869F320
	cry2 Cry_Titenic  @ 869F32C
	cry2 Cry_Gummi  @ 869F338
	cry2 Cry_Muk  @ 869F344
	cry2 Cry_Coolar  @ 869F350
	cry2 Cry_Fridege  @ 869F35C
	cry2 Cry_Skeledoot  @ 869F368
	cry2 Cry_Beegmike  @ 869F374
	cry2 Cry_Sans  @ 869F380
	cry2 Cry_Esceepee  @ 869F38C
	cry2 Cry_Shapipiz  @ 869F398
	cry2 Cry_Shapoopyz  @ 869F3A4
	cry2 Cry_Stroloke  @ 869F3B0
	cry2 Cry_Creepa  @ 869F3BC
	cry2 Cry_Awmane  @ 869F3C8
	cry2 Cry_Endermon  @ 869F3D4
	cry2 Cry_Billominat  @ 869F3E0
	cry2 Cry_Ciphron  @ 869F3EC
	cry2 Cry_Surbsquach  @ 869F3F8
	cry2 Cry_Amazulk  @ 869F404
	cry2 Cry_Replitor  @ 869F410
	cry2 Cry_Biremic  @ 869F41C
	cry2 Cry_Capfalco  @ 869F428
	cry2 Cry_Fennaf  @ 869F434
	cry2 Cry_Bipharma  @ 869F440
	cry2 Cry_Potogreed  @ 869F44C
	cry2 Cry_Yeesaur  @ 869F458
	cry2 Cry_Unjoy  @ 869F464
	cry2 Cry_Bananace  @ 869F470
	cry2 Cry_Trololo  @ 869F47C
	cry2 Cry_Jank  @ 869F488
	cry2 Cry_Swampogre  @ 869F494
	cry2 Cry_Cighted  @ 869F4A0
	cry2 Cry_Mongelord  @ 869F4AC
	cry2 Cry_Burik  @ 869F4B8
	cry2 Cry_Bicyelion  @ 869F4C4
	cry2 Cry_Alien  @ 869F4D0
	cry2 Cry_Chuxkush  @ 869F4DC
	cry2 Cry_Repsac  @ 869F4E8
	cry2 Cry_Krafpunk  @ 869F4F4
	cry2 Cry_Endmysuff  @ 869F500
	cry2 Cry_Itrimid  @ 869F50C
	cry2 Cry_Grox  @ 869F518
	cry2 Cry_Nushake  @ 869F524
	cry2 Cry_Kroller  @ 869F530
	cry2 Cry_Jebony  @ 869F53C
	cry2 Cry_Ditto  @ 869F548
	cry2 Cry_Eemojee  @ 869F554
	cry2 Cry_Stresseon  @ 869F560
	cry2 Cry_Xokkeon  @ 869F56C
	cry2 Cry_Babeyon  @ 869F578
	cry2 Cry_Auricliary  @ 869F584
	cry2 Cry_Attaco  @ 869F590
	cry2 Cry_Gaiser  @ 869F59C
	cry2 Cry_Corork  @ 869F5A8
	cry2 Cry_Bigobeet  @ 869F5B4
	cry2 Cry_Usarmy  @ 869F5C0
	cry2 Cry_Shepeird  @ 869F5CC
	cry2 Cry_Legend  @ 869F5D8
	cry2 Cry_Zeruel  @ 869F5E4
	cry2 Cry_Remiel  @ 869F5F0
	cry2 Cry_Amonsus  @ 869F5FC
	cry2 Cry_Wooptret  @ 869F608
	cry2 Cry_Killworu  @ 869F614
	cry2 Cry_God  @ 869F620
	cry2 Cry_Thevoid  @ 869F62C
	cry2 Cry_Tom  @ 869F638
	cry2 Cry_Zactory  @ 869F644
	cry2 Cry_Rammet  @ 869F650
	cry2 Cry_Megatron  @ 869F65C
	cry2 Cry_Rigamort  @ 869F668
	cry2 Cry_Rickle  @ 869F674
	cry2 Cry_Korbie  @ 869F680
	cry2 Cry_Jewis  @ 869F68C
	cry2 Cry_Teed  @ 869F698
	cry2 Cry_Goncariciv  @ 869F6A4
	cry2 Cry_Deepfrieon  @ 869F6B0
	cry2 Cry_WormadamT  @ 869F6BC
	cry2 Cry_Jadoug  @ 869F6C8
	cry2 Cry_Abominaton  @ 869F6D4
	cry2 Cry_Wurm  @ 869F6E0
	cry2 Cry_Phracer  @ 869F6EC
	cry2 Cry_Gluerilla  @ 869F6F8
	cry2 Cry_Luis  @ 869F704
	cry2 Cry_Lovlilad  @ 869F710
	cry2 Cry_Ourobolet  @ 869F71C
	cry2 Cry_Pichu  @ 869F728
	cry2 Cry_Pooprat  @ 869F734
	cry2 Cry_Vcrbrain  @ 869F740
	cry2 Cry_Filmbrain  @ 869F74C
	cry2 Cry_Blurabrain  @ 869F758
	cry2 Cry_Puckid  @ 869F764
	cry2 Cry_Goalem  @ 869F770
	cry2 Cry_Baddery  @ 869F77C
	cry2 Cry_Durashell  @ 869F788
	cry2 Cry_Bacid  @ 869F794
	cry2 Cry_Seawee  @ 869F7A0
	cry2 Cry_Seakush  @ 869F7AC
	cry2 Cry_Barireefer  @ 869F7B8
	cry2 Cry_Breaddie  @ 869F7C4
	cry2 Cry_Toastem  @ 869F7D0
	cry2 Cry_Dogeaster  @ 869F7DC
	cry2 Cry_Anoobis  @ 869F7E8
	cry2 Cry_Nightwave  @ 869F7F4
	cry2 Cry_Charles  @ 869F800
	cry2 Cry_Melarick  @ 869F80C
	cry2 Cry_Wreckfast  @ 869F818
	cry2 Cry_Sharcrush  @ 869F824
	cry2 Cry_Megaladeth  @ 869F830
	cry2 Cry_Arealgun  @ 869F83C
	cry2 Cry_Dont  @ 869F848
	cry2 Cry_Leave  @ 869F854
	cry2 Cry_Gahblin  @ 869F860
	cry2 Cry_Gooblan  @ 869F86C
	cry2 Cry_Lilreaper  @ 869F878
	cry2 Cry_Unown  @ 869F884
	cry2 Cry_Firant  @ 869F890
	cry2 Cry_Burnant  @ 869F89C
	cry2 Cry_Antinder  @ 869F8A8
	cry2 Cry_Waile  @ 869F8B4
	cry2 Cry_Moaby  @ 869F8C0
	cry2 Cry_Shawt  @ 869F8CC
	cry2 Cry_Holocast  @ 869F8D8
	cry2 Cry_Grubdab  @ 869F8E4
	cry2 Cry_Dabbug  @ 869F8F0
	cry2 Cry_Dabbeatle  @ 869F8FC
	cry2 Cry_Nuggie  @ 869F908
	cry2 Cry_Mcchicky  @ 869F914
	cry2 Cry_Happymaul  @ 869F920
	cry2 Cry_Pinati  @ 869F92C
	cry2 Cry_Vivapinaut  @ 869F938
	cry2 Cry_Maurrice  @ 869F944
	cry2 Cry_Slugma  @ 869F950
	cry2 Cry_Sugmaballs  @ 869F95C
	cry2 Cry_Orcale  @ 869F968
	cry2 Cry_Scrapchat  @ 869F974
	cry2 Cry_Setronic  @ 869F980
	cry2 Cry_Bannaconda  @ 869F98C
	cry2 Cry_Systanic  @ 869F998
	cry2 Cry_Abstratic  @ 869F9A4
	cry2 Cry_Flooticorn  @ 869F9B0
	cry2 Cry_Legearth  @ 869F9BC
	cry2 Cry_Leguessr  @ 869F9C8
	cry2 Cry_Minimal  @ 869F9D4
	cry2 Cry_Dismalo  @ 869F9E0
	cry2 Cry_Mortarmalo  @ 869F9EC
	cry2 Cry_Cofficrab  @ 869F9F8
	cry2 Cry_Craberave  @ 869FA04
	cry2 Cry_Gnorb  @ 869FA10
	cry2 Cry_Gahnomed  @ 869FA1C
	cry2 Cry_Drywee  @ 869FA28
	cry2 Cry_Straidirt  @ 869FA34
	cry2 Cry_Burntonion  @ 869FA40
	cry2 Cry_Platerry  @ 869FA4C
	cry2 Cry_Rickling  @ 869FA58
	cry2 Cry_Pants  @ 869FA64
	cry2 Cry_Reapcharge  @ 869FA70
	cry2 Cry_Shockitty  @ 869FA7C
	cry2 Cry_Heattar  @ 869FA88
	cry2 Cry_Reingeer  @ 869FA94
	cry2 Cry_Frosling  @ 869FAA0
	cry2 Cry_Froshund  @ 869FAAC
	cry2 Cry_Frosilisk  @ 869FAB8
	cry2 Cry_Helpme  @ 869FAC4
	cry2 Cry_Suffer  @ 869FAD0
	cry2 Cry_Lilguy  @ 869FADC
	cry2 Cry_Berryalen
	cry2 Cry_Veryberry
	cry2 Cry_Incredalen
	cry2 Cry_Cooklet
	cry2 Cry_Chefure
	cry2 Cry_Gourmaster
	cry2 Cry_Baitord
	cry2 Cry_Baiterror
	cry2 Cry_Baitank
	cry2 Cry_Duplicat
	cry2 Cry_Furrlead
	cry2 Cry_Meowrrior
	cry2 Cry_Zeppur
	cry2 Cry_Zepurrine
	cry2 Cry_Nyankitty
	cry2 Cry_Nyantiger
	cry2 Cry_Mechduck
	cry2 Cry_Duckertron
	cry2 Cry_Scubite
	cry2 Cry_Quackshot
	cry2 Cry_Quacknator
	cry2 Cry_Sobbleaf
	cry2 Cry_Herokku
	cry2 Cry_Shadeku
	cry2 Cry_Taillow
	cry2 Cry_Xapp
	cry2 Cry_Batcardi
	cry2 Cry_Noctrum
	cry2 Cry_Notafurry
	cry2 Cry_Sortafurry
	cry2 Cry_Thatsfurry
	cry2 Cry_Whiskball
	cry2 Cry_Cinamancer
	cry2 Cry_Blinky
	cry2 Cry_Doublinker
	cry2 Cry_Doobob
	cry2 Cry_Doodoobob
	cry2 Cry_Ugadooba
	cry2 Cry_Nincada
	cry2 Cry_Ninjask
	cry2 Cry_Shedinja
	cry2 Cry_Cowerlin
	cry2 Cry_Bravogor
	cry2 Cry_Gigalpha
	cry2 Cry_Angbeast
	cry2 Cry_Gangbeats
	cry2 Cry_Azurill
	cry2 Cry_Scatrush
	cry2 Cry_Smoslime
	cry2 Cry_Nyancat
	cry2 Cry_Secritler
	cry2 Cry_Minitron
	cry2 Cry_Aron
	cry2 Cry_Galvatron
	cry2 Cry_Murphire
	cry2 Cry_Lonk
	cry2 Cry_Lonkest
	cry2 Cry_Cordra
	cry2 Cry_Auxilisk
	cry2 Cry_Purrsour
	cry2 Cry_Purrtang
	cry2 Cry_Rewindle
	cry2 Cry_Dndice
	cry2 Cry_Alieon
	cry2 Cry_Symbite
	cry2 Cry_Carnigore
	cry2 Cry_Brewfin
	cry2 Cry_Sharkeg
	cry2 Cry_Shrimpot
	cry2 Cry_Lobscald
	cry2 Cry_Vulpointer
	cry2 Cry_Errorine
	cry2 Cry_Hellaphant
	cry2 Cry_Fizzcub
	cry2 Cry_Seltclaw
	cry2 Cry_Yeltzer
	cry2 Cry_Metiore
	cry2 Cry_Cometide
	cry2 Cry_Galadrake
	cry2 Cry_Yolkanner
	cry2 Cry_Aconeggs
	cry2 Cry_Armydrone
	cry2 Cry_UNSC
	cry2 Cry_Smitnion
	cry2 Cry_Arackne
	cry2 Cry_Surtyur
	cry2 Cry_Ganesh
	cry2 Cry_Coopid
	cry2 Cry_Splashicoot
	cry2 Cry_Nongetive
	cry2 Cry_Nononmon
	cry2 Cry_Dreidrill
	cry2 Cry_Heburrow
	cry2 Cry_Odosaur
	cry2 Cry_Pyrabass
	cry2 Cry_Triceras
	cry2 Cry_Xenotops
	cry2 Cry_Paddlite
	cry2 Cry_Nutvalanche
	cry2 Cry_Castform
	cry2 Cry_Kecleon
	cry2 Cry_Ticktowel
	cry2 Cry_Tocktower
	cry2 Cry_Ratman
	cry2 Cry_Hugeman
	cry2 Cry_Tropius
	cry2 Cry_Kirbairde
	cry2 Cry_Fredbar
	cry2 Cry_Babinion
	cry2 Cry_Chairold
	cry2 Cry_Elechair
	cry2 Cry_Piraghoul
	cry2 Cry_Morghost
	cry2 Cry_Phasmorgan
	cry2 Cry_Golbnar
	cry2 Cry_Globnaut
	cry2 Cry_Thaumnar
	cry2 Cry_Galacnar
	cry2 Cry_Warpnar
	cry2 Cry_Sipking
	cry2 Cry_Tipsyramid
	cry2 Cry_Drunkabus
	cry2 Cry_Yelleye
	cry2 Cry_Harastur
	cry2 Cry_Hazethoth
	cry2 Cry_Regirock
	cry2 Cry_Regice
	cry2 Cry_Nawffle
	cry2 Cry_Latias
	cry2 Cry_Latios
	cry2 Cry_Krakrum
	cry2 Cry_Noirnet
	cry2 Cry_Rayquaza
	cry2 Cry_Thiscraker
	cry2 Cry_Deoxys
@ Gen 4
	cry2_not Cry_Turtwig
	cry2_not Cry_Grotle
	cry2_not Cry_Torterra
	cry2_not Cry_Embob
	cry2_not Cry_Coalgar
	cry2_not Cry_Bobistic
	cry2_not Cry_Oroflow
	cry2_not Cry_Orocast
	cry2_not Cry_Orrowhelm
	cry2_not Cry_Starly
	cry2_not Cry_Staravia
	cry2_not Cry_Staraptor
	cry2_not Cry_Xdik
	cry2_not Cry_Xdemon
	cry2_not Cry_Desitrus
	cry2_not Cry_Desqueeze
	cry2_not Cry_Shinx
	cry2_not Cry_Luxio
	cry2_not Cry_Luxray
	cry2_not Cry_Banslip
	cry2_not Cry_Roserade
	cry2_not Cry_Cranidos
	cry2_not Cry_Rampardos
	cry2_not Cry_Shieldon
	cry2_not Cry_Bastiodon
	cry2_not Cry_Parslito
	cry2_not Cry_Mojisley
	cry2_not Cry_Gailord
	cry2_not Cry_Combee
	cry2_not Cry_Vespiquen
	cry2_not Cry_Pachirisu
	cry2_not Cry_Squigga
	cry2_not Cry_Desparward
	cry2_not Cry_Bushizard
	cry2_not Cry_Notyuhdad
	cry2_not Cry_Choccudle
	cry2_not Cry_Choctic
	cry2_not Cry_Ambipom
	cry2_not Cry_Drifloon
	cry2_not Cry_Drifblim
	cry2_not Cry_Buneary
	cry2_not Cry_Lopunny
	cry2_not Cry_Mismagius
	cry2_not Cry_Honchkrow
	cry2_not Cry_Glameow
	cry2_not Cry_Gorfold
	cry2_not Cry_Luiwee
	cry2_not Cry_Stunky
	cry2_not Cry_Skuntank
	cry2_not Cry_Bronzor
	cry2_not Cry_Bronzong
	cry2_not Cry_Bonsly
	cry2_not Cry_Mimejr
	cry2_not Cry_Hangingy
	cry2_not Cry_Enderagon
	cry2_not Cry_Chancer
	cry2_not Cry_Capple
	cry2_not Cry_Shellhaul
	cry2_not Cry_Truckoise
	cry2_not Cry_Trololing
	cry2_not Cry_Brixel
	cry2_not Cry_Bloknock
	cry2_not Cry_Journemap
	cry2_not Cry_Journeship
	cry2_not Cry_Skorupi
	cry2_not Cry_Drapion
	cry2_not Cry_Croagunk
	cry2_not Cry_Toxicroak
	cry2_not Cry_Carnivine
	cry2_not Cry_Finneon
	cry2_not Cry_Lumineon
	cry2_not Cry_Mantyke
	cry2_not Cry_Snover
	cry2_not Cry_Abomasnow
	cry2_not Cry_Fredunkle
	cry2_not Cry_Magnezone
	cry2_not Cry_Lickilicky
	cry2_not Cry_Rhyperior
	cry2_not Cry_Tangrowth
	cry2_not Cry_Electivire
	cry2_not Cry_Toastrider
	cry2_not Cry_Togekiss
	cry2_not Cry_Yanmega
	cry2_not Cry_Leafeon
	cry2_not Cry_Glaceon
	cry2_not Cry_Gliscor
	cry2_not Cry_Mamoswine
	cry2_not Cry_Hellspack
	cry2_not Cry_Gallade
	cry2_not Cry_Probopass
	cry2_not Cry_Skeledoom
	cry2_not Cry_Blinkrupt
	cry2_not Cry_Rotom
	cry2_not Cry_Uxie
	cry2_not Cry_Mesprit
	cry2_not Cry_Azelf
	cry2_not Cry_Dialga
	cry2_not Cry_Palkia
	cry2_not Cry_Heatran
	cry2_not Cry_Regigigas
	cry2_not Cry_Giratina
	cry2_not Cry_Cresselia
	cry2_not Cry_Phione
	cry2_not Cry_Manaphy
	cry2_not Cry_Darkrai
	cry2_not Cry_Shaymin
	cry2_not Cry_Arceus
	@ Gen 5
	cry2_not Cry_Victini
	cry2_not Cry_Snivy
	cry2_not Cry_Servine
	cry2_not Cry_Serperior
	cry2_not Cry_Tepig
	cry2_not Cry_Pignite
	cry2_not Cry_Emboar
	cry2_not Cry_Oshawott
	cry2_not Cry_Dewott
	cry2_not Cry_Samurott
	cry2_not Cry_Patrat
	cry2_not Cry_Watchog
	cry2_not Cry_Lillipup
	cry2_not Cry_Herdier
	cry2_not Cry_Stoutland
	cry2_not Cry_Purrloin
	cry2_not Cry_Liepard
	cry2_not Cry_Pansage
	cry2_not Cry_Simisage
	cry2_not Cry_Pansear
	cry2_not Cry_Simisear
	cry2_not Cry_Panpour
	cry2_not Cry_Simipour
	cry2_not Cry_Munna
	cry2_not Cry_Musharna
	cry2_not Cry_Pidove
	cry2_not Cry_Tranquill
	cry2_not Cry_Unfezant
	cry2_not Cry_Blitzle
	cry2_not Cry_Zebstrika
	cry2_not Cry_Roggenrola
	cry2_not Cry_Boldore
	cry2_not Cry_Gigalith
	cry2_not Cry_Woobat
	cry2_not Cry_Swoobat
	cry2_not Cry_Drilbur
	cry2_not Cry_Excadrill
	cry2_not Cry_Audino
	cry2_not Cry_Timburr
	cry2_not Cry_Gurdurr
	cry2_not Cry_Conkeldurr
	cry2_not Cry_Tympole
	cry2_not Cry_Palpitoad
	cry2_not Cry_Seismitoad
	cry2_not Cry_Throh
	cry2_not Cry_Sawk
	cry2_not Cry_Sewaddle
	cry2_not Cry_Swadloon
	cry2_not Cry_Leavanny
	cry2_not Cry_Venipede
	cry2_not Cry_Whirlipede
	cry2_not Cry_Scolipede
	cry2_not Cry_Cottonee
	cry2_not Cry_Whimsicott
	cry2_not Cry_Petilil
	cry2_not Cry_Lilligant
	cry2_not Cry_Basculin
	cry2_not Cry_Sandile
	cry2_not Cry_Krokorok
	cry2_not Cry_Krookodile
	cry2_not Cry_Darumaka
	cry2_not Cry_Darmanitan
	cry2_not Cry_Maractus
	cry2_not Cry_Dwebble
	cry2_not Cry_Crustle
	cry2_not Cry_Scraggy
	cry2_not Cry_Scrafty
	cry2_not Cry_Sigilyph
	cry2_not Cry_Yamask
	cry2_not Cry_Cofagrigus
	cry2_not Cry_Tirtouga
	cry2_not Cry_Carracosta
	cry2_not Cry_Archen
	cry2_not Cry_Archeops
	cry2_not Cry_Trubbish
	cry2_not Cry_Garbodor
	cry2_not Cry_Zorua
	cry2_not Cry_Zoroark
	cry2_not Cry_Minccino
	cry2_not Cry_Cinccino
	cry2_not Cry_Gothita
	cry2_not Cry_Gothorita
	cry2_not Cry_Gothitelle
	cry2_not Cry_Solosis
	cry2_not Cry_Duosion
	cry2_not Cry_Reuniclus
	cry2_not Cry_Ducklett
	cry2_not Cry_Swanna
	cry2_not Cry_Vanillite
	cry2_not Cry_Vanillish
	cry2_not Cry_Vanilluxe
	cry2_not Cry_Deerling
	cry2_not Cry_Sawsbuck
	cry2_not Cry_Emolga
	cry2_not Cry_Karrablast
	cry2_not Cry_Escavalier
	cry2_not Cry_Foongus
	cry2_not Cry_Amoonguss
	cry2_not Cry_Frillish
	cry2_not Cry_Jellicent
	cry2_not Cry_Alomomola
	cry2_not Cry_Joltik
	cry2_not Cry_Galvantula
	cry2_not Cry_Ferroseed
	cry2_not Cry_Ferrothorn
	cry2_not Cry_Klink
	cry2_not Cry_Klang
	cry2_not Cry_Klinklang
	cry2_not Cry_Tynamo
	cry2_not Cry_Eelektrik
	cry2_not Cry_Eelektross
	cry2_not Cry_Elgyem
	cry2_not Cry_Beheeyem
	cry2_not Cry_Litwick
	cry2_not Cry_Lampent
	cry2_not Cry_Chandelure
	cry2_not Cry_Axew
	cry2_not Cry_Fraxure
	cry2_not Cry_Haxorus
	cry2_not Cry_Cubchoo
	cry2_not Cry_Beartic
	cry2_not Cry_Cryogonal
	cry2_not Cry_Shelmet
	cry2_not Cry_Accelgor
	cry2_not Cry_Stunfisk
	cry2_not Cry_Mienfoo
	cry2_not Cry_Mienshao
	cry2_not Cry_Druddigon
	cry2_not Cry_Golett
	cry2_not Cry_Golurk
	cry2_not Cry_Pawniard
	cry2_not Cry_Bisharp
	cry2_not Cry_Bouffalant
	cry2_not Cry_Rufflet
	cry2_not Cry_Braviary
	cry2_not Cry_Vullaby
	cry2_not Cry_Mandibuzz
	cry2_not Cry_Heatmor
	cry2_not Cry_Durant
	cry2_not Cry_Deino
	cry2_not Cry_Zweilous
	cry2_not Cry_Hydreigon
	cry2_not Cry_Larvesta
	cry2_not Cry_Volcarona
	cry2_not Cry_Cobalion
	cry2_not Cry_Terrakion
	cry2_not Cry_Virizion
	cry2_not Cry_Tornadus
	cry2_not Cry_Thundurus
	cry2_not Cry_Reshiram
	cry2_not Cry_Zekrom
	cry2_not Cry_Landorus
	cry2_not Cry_Kyurem
	cry2_not Cry_Keldeo
	cry2_not Cry_Meloetta
	cry2_not Cry_Genesect
	@ Gen 6
	cry2_not Cry_Chespin
	cry2_not Cry_Quilladin
	cry2_not Cry_Chesnaught
	cry2_not Cry_Fennekin
	cry2_not Cry_Braixen
	cry2_not Cry_Delphox
	cry2_not Cry_Froakie
	cry2_not Cry_Frogadier
	cry2_not Cry_Greninja
	cry2_not Cry_Bunnelby
	cry2_not Cry_Diggersby
	cry2_not Cry_Fletchling
	cry2_not Cry_Fletchinder
	cry2_not Cry_Talonflame
	cry2_not Cry_Scatterbug
	cry2_not Cry_Spewpa
	cry2_not Cry_Vivillon
	cry2_not Cry_Litleo
	cry2_not Cry_Pyroar
	cry2_not Cry_Flabebe
	cry2_not Cry_Floette
	cry2_not Cry_Florges
	cry2_not Cry_Skiddo
	cry2_not Cry_Gogoat
	cry2_not Cry_Pancham
	cry2_not Cry_Pangoro
	cry2_not Cry_Furfrou
	cry2_not Cry_Espurr
	cry2_not Cry_Meowstic
	cry2_not Cry_Honedge
	cry2_not Cry_Doublade
	cry2_not Cry_Aegislash
	cry2_not Cry_Spritzee
	cry2_not Cry_Aromatisse
	cry2_not Cry_Swirlix
	cry2_not Cry_Slurpuff
	cry2_not Cry_Inkay
	cry2_not Cry_Malamar
	cry2_not Cry_Binacle
	cry2_not Cry_Barbaracle
	cry2_not Cry_Skrelp
	cry2_not Cry_Dragalge
	cry2_not Cry_Clauncher
	cry2_not Cry_Clawitzer
	cry2_not Cry_Helioptile
	cry2_not Cry_Heliolisk
	cry2_not Cry_Tyrunt
	cry2_not Cry_Tyrantrum
	cry2_not Cry_Amaura
	cry2_not Cry_Aurorus
	cry2_not Cry_Sylveon
	cry2_not Cry_Hawlucha
	cry2_not Cry_Dedenne
	cry2_not Cry_Carbink
	cry2_not Cry_Goomy
	cry2_not Cry_Sliggoo
	cry2_not Cry_Goodra
	cry2_not Cry_Klefki
	cry2_not Cry_Phantump
	cry2_not Cry_Trevenant
	cry2_not Cry_Pumpkaboo
	cry2_not Cry_Gourgeist
	cry2_not Cry_Bergmite
	cry2_not Cry_Avalugg
	cry2_not Cry_Noibat
	cry2_not Cry_Noivern
	cry2_not Cry_Xerneas
	cry2_not Cry_Yveltal
	cry2_not Cry_Zygarde
	cry2_not Cry_Diancie
	cry2_not Cry_Hoopa
	cry2_not Cry_Volcanion
	@ Gen 7
	cry2_not Cry_Rowlet
	cry2_not Cry_Dartrix
	cry2_not Cry_Decidueye
	cry2_not Cry_Litten
	cry2_not Cry_Torracat
	cry2_not Cry_Incineroar
	cry2_not Cry_Popplio
	cry2_not Cry_Brionne
	cry2_not Cry_Primarina
	cry2_not Cry_Pikipek
	cry2_not Cry_Trumbeak
	cry2_not Cry_Toucannon
	cry2_not Cry_Yungoos
	cry2_not Cry_Gumshoos
	cry2_not Cry_Grubbin
	cry2_not Cry_Charjabug
	cry2_not Cry_Vikavolt
	cry2_not Cry_Crabrawler
	cry2_not Cry_Crabominable
	cry2_not Cry_Oricorio
	cry2_not Cry_Cutiefly
	cry2_not Cry_Ribombee
	cry2_not Cry_Rockruff
	cry2_not Cry_Lycanroc
	cry2_not Cry_Wishiwashi
	cry2_not Cry_Mareanie
	cry2_not Cry_Toxapex
	cry2_not Cry_Mudbray
	cry2_not Cry_Mudsdale
	cry2_not Cry_Dewpider
	cry2_not Cry_Araquanid
	cry2_not Cry_Fomantis
	cry2_not Cry_Lurantis
	cry2_not Cry_Morelull
	cry2_not Cry_Shiinotic
	cry2_not Cry_Salandit
	cry2_not Cry_Salazzle
	cry2_not Cry_Stufful
	cry2_not Cry_Bewear
	cry2_not Cry_Bounsweet
	cry2_not Cry_Steenee
	cry2_not Cry_Tsareena
	cry2_not Cry_Comfey
	cry2_not Cry_Oranguru
	cry2_not Cry_Passimian
	cry2_not Cry_Wimpod
	cry2_not Cry_Golisopod
	cry2_not Cry_Sandygast
	cry2_not Cry_Palossand
	cry2_not Cry_Pyukumuku
	cry2_not Cry_Type_null
	cry2_not Cry_Silvally
	cry2_not Cry_Minior
	cry2_not Cry_Komala
	cry2_not Cry_Turtonator
	cry2_not Cry_Togedemaru
	cry2_not Cry_Mimikyu
	cry2_not Cry_Bruxish
	cry2_not Cry_Drampa
	cry2_not Cry_Dhelmise
	cry2_not Cry_Jangmo_o
	cry2_not Cry_Hakamo_o
	cry2_not Cry_Kommo_o
	cry2_not Cry_Tapu_koko
	cry2_not Cry_Tapu_lele
	cry2_not Cry_Tapu_bulu
	cry2_not Cry_Tapu_fini
	cry2_not Cry_Cosmog
	cry2_not Cry_Cosmoem
	cry2_not Cry_Solgaleo
	cry2_not Cry_Lunala
	cry2_not Cry_Nihilego
	cry2_not Cry_Buzzwole
	cry2_not Cry_Pheromosa
	cry2_not Cry_Xurkitree
	cry2_not Cry_Celesteela
	cry2_not Cry_Kartana
	cry2_not Cry_Guzzlord
	cry2_not Cry_Necrozma
	cry2_not Cry_Magearna
	cry2_not Cry_Marshadow
	cry2_not Cry_Poipole
	cry2_not Cry_Naganadel
	cry2_not Cry_Stakataka
	cry2_not Cry_Blacephalon
	cry2_not Cry_Zeraora
	cry2_not Cry_Meltan
	cry2_not Cry_Melmetal
	cry2_not Cry_Grookey
	cry2_not Cry_Thwackey
	cry2_not Cry_Rillaboom
	cry2_not Cry_Scorbunny
	cry2_not Cry_Raboot
	cry2_not Cry_Cinderace
	cry2_not Cry_Sobble
	cry2_not Cry_Drizzile
	cry2_not Cry_Inteleon
	cry2_not Cry_Skwovet
	cry2_not Cry_Greedent
	cry2_not Cry_Rookidee
	cry2_not Cry_Corvisquire
	cry2_not Cry_Corviknight
	cry2_not Cry_Blipbug
	cry2_not Cry_Dottler
	cry2_not Cry_Orbeetle
	cry2_not Cry_Nickit
	cry2_not Cry_Thievul
	cry2_not Cry_Gossifleur
	cry2_not Cry_Eldegoss
	cry2_not Cry_Wooloo
	cry2_not Cry_Dubwool
	cry2_not Cry_Chewtle
	cry2_not Cry_Drednaw
	cry2_not Cry_Yamper
	cry2_not Cry_Boltund
	cry2_not Cry_Rolycoly
	cry2_not Cry_Carkol
	cry2_not Cry_Coalossal
	cry2_not Cry_Applin
	cry2_not Cry_Flapple
	cry2_not Cry_Appletun
	cry2_not Cry_Silicobra
	cry2_not Cry_Sandaconda
	cry2_not Cry_Cramorant
	cry2_not Cry_Arrokuda
	cry2_not Cry_Barraskewda
	cry2_not Cry_Toxel
	cry2_not Cry_Toxtricity
	cry2_not Cry_Sizzlipede
	cry2_not Cry_Centiskorch
	cry2_not Cry_Clobbopus
	cry2_not Cry_Grapploct
	cry2_not Cry_Sinistea
	cry2_not Cry_Polteageist
	cry2_not Cry_Hatenna
	cry2_not Cry_Hattrem
	cry2_not Cry_Hatterene
	cry2_not Cry_Impidimp
	cry2_not Cry_Morgrem
	cry2_not Cry_Grimmsnarl
	cry2_not Cry_Obstagoon
	cry2_not Cry_Perrserker
	cry2_not Cry_Cursola
	cry2_not Cry_Sirfetchd
	cry2_not Cry_MrRime
	cry2_not Cry_Runerigus
	cry2_not Cry_Milcery
	cry2_not Cry_Alcremie
	cry2_not Cry_Falinks
	cry2_not Cry_Pincurchin
	cry2_not Cry_Snom
	cry2_not Cry_Frosmoth
	cry2_not Cry_Stonjourner
	cry2_not Cry_Eiscue
	cry2_not Cry_Indeedee
	cry2_not Cry_Morpeko
	cry2_not Cry_Cufant
	cry2_not Cry_Copperajah
	cry2_not Cry_Dracozolt
	cry2_not Cry_Arctozolt
	cry2_not Cry_Dracovish
	cry2_not Cry_Arctovish
	cry2_not Cry_Duraludon
	cry2_not Cry_Dreepy
	cry2_not Cry_Drakloak
	cry2_not Cry_Dragapult
	cry2_not Cry_Zacian
	cry2_not Cry_Zamazenta
	cry2_not Cry_Eternatus
	cry2_not Cry_Kubfu
	cry2_not Cry_Urshifu
	cry2_not Cry_Zarude
	cry2_not Cry_Regieleki
	cry2_not Cry_Regidrago
	cry2_not Cry_Glastrier
	cry2_not Cry_Spectrier
	cry2_not Cry_Calyrex
	@ Megas
	cry2_not Cry_Yggdracon_Mega
	cry2_not Cry_Skorpyros_Mega_X
	cry2_not Cry_Skorpyros_Mega_Y
	cry2_not Cry_Speriathon_Mega
	cry2_not Cry_BIPHARMA_MEGA
	cry2_not Cry_Bug_Mega
	cry2_not Cry_Gothot_Mega
	cry2_not Cry_Dushroom_Mega
	cry2_not Cry_Jank_Mega
	cry2_not Cry_Rock_Mega
	cry2_not Cry_Shepeird_Mega
	cry2_not Cry_Sneddit_Mega
	cry2_not Cry_Tom_Mega
	cry2_not Cry_God_Mega_X
	cry2_not Cry_God_Mega_Y
	cry2_not Cry_Thevoid_Mega
	cry2_not Cry_Gigalpha_Mega
	cry2_not Cry_Gahnomed_Mega
	cry2_not Cry_Goalem_Mega
	cry2_not Cry_Incredalen_Mega
	cry2_not Cry_Gourmaster_Mega
	cry2_not Cry_Baitank_Mega
	cry2_not Cry_Awmane_Mega
	cry2_not Cry_Secritler_Mega
	cry2_not Cry_Minitron_Mega
	cry2_not Cry_Murphire_Mega
	cry2_not Cry_Lonkest_Mega
	cry2_not Cry_Auxilisk_Mega
	cry2_not Cry_Sharkeg_Mega
	cry2_not Cry_Errorine_Mega
	cry2_not Cry_UNSC_Mega
	cry2_not Cry_Tocktower_Mega
	cry2_not Cry_Fredbar_Mega
	cry2_not Cry_Elechair_Mega
	cry2_not Cry_Drunkabus_Mega
	cry2_not Cry_Hazethoth_Mega
	cry2_not Cry_Latias_Mega
	cry2_not Cry_Latios_Mega
	cry2_not Cry_Lopunny_Mega
	cry2_not Cry_Truckoise_Mega
	cry2_not Cry_Bloknock_Mega
	cry2_not Cry_Abomasnow_Mega
	cry2_not Cry_Gallade_Mega
	cry2_not Cry_UNJOY_MEGA
	cry2_not Cry_Diancie_Mega
	@ Special Mega + Primals
	cry2_not Cry_Rayquaza_Mega
	cry2_not Cry_Krakrum_Primal
	cry2_not Cry_Noirnet_Primal
	@ Alolan Forms
	cry2 Cry_Hangster
	cry2 Cry_Gawdamster
	cry2 Cry_Disheats
	cry2 Cry_Jafeet
	cry2 Cry_Toyuta
	cry2 Cry_Saucie
	cry2 Cry_Sawsbaws
	cry2 Cry_Diglett
	cry2 Cry_Ghoma
	cry2 Cry_Garfel
	cry2 Cry_Gorefield
	cry2 Cry_Rock
	cry2 Cry_Toncrete
	cry2 Cry_Lossilith
	cry2 Cry_Gummi
	cry2 Cry_Muk
	cry2 Cry_Ciphron
	cry2 Cry_Amazulk
	@ Galarian Forms
	cry2 Cry_Garfel
	cry2 Cry_Debeguck
	cry2 Cry_Lonky
	cry2_not Cry_Basshop_Galarian
	cry2 Cry_Shemue
	cry2 Cry_Impostown
	cry2 Cry_Bipharma
	cry2 Cry_Alien
	cry2 Cry_Legend
	cry2 Cry_Zeruel
	cry2 Cry_Remiel
	cry2 Cry_Gooblan
	cry2 Cry_Setronic
	cry2 Cry_Meowrrior
	cry2 Cry_Zeppur
	cry2_not Cry_Darumaka
	cry2_not Cry_Darmanitan
	cry2_not Cry_Yamask
	cry2_not Cry_Stunfisk
	@ Misc Forms
	@ Cosplay Skippa
	cry2 Cry_Skippa  @ 869DE14
	cry2 Cry_Skippa  @ 869DE14
	cry2 Cry_Skippa  @ 869DE14
	cry2 Cry_Skippa  @ 869DE14
	cry2 Cry_Skippa  @ 869DE14
	cry2 Cry_Skippa  @ 869DE14
	@ Cap Skippa
	cry2 Cry_Skippa  @ 869DE14
	cry2 Cry_Skippa  @ 869DE14
	cry2 Cry_Skippa  @ 869DE14
	cry2 Cry_Skippa  @ 869DE14
	cry2 Cry_Skippa  @ 869DE14
	cry2 Cry_Skippa  @ 869DE14
	cry2 Cry_Skippa  @ 869DE14
	cry2 Cry_Skippa  @ 869DE14
	@ Pichu
	cry2 Cry_Pichu  @ 869E4F8
	@ Unown
	cry2 Cry_Unown  @ 869E654
	cry2 Cry_Unown  @ 869E654
	cry2 Cry_Unown  @ 869E654
	cry2 Cry_Unown  @ 869E654
	cry2 Cry_Unown  @ 869E654
	cry2 Cry_Unown  @ 869E654
	cry2 Cry_Unown  @ 869E654
	cry2 Cry_Unown  @ 869E654
	cry2 Cry_Unown  @ 869E654
	cry2 Cry_Unown  @ 869E654
	cry2 Cry_Unown  @ 869E654
	cry2 Cry_Unown  @ 869E654
	cry2 Cry_Unown  @ 869E654
	cry2 Cry_Unown  @ 869E654
	cry2 Cry_Unown  @ 869E654
	cry2 Cry_Unown  @ 869E654
	cry2 Cry_Unown  @ 869E654
	cry2 Cry_Unown  @ 869E654
	cry2 Cry_Unown  @ 869E654
	cry2 Cry_Unown  @ 869E654
	cry2 Cry_Unown  @ 869E654
	cry2 Cry_Unown  @ 869E654
	cry2 Cry_Unown  @ 869E654
	cry2 Cry_Unown  @ 869E654
	cry2 Cry_Unown  @ 869E654
	cry2 Cry_Unown  @ 869E654
	cry2 Cry_Unown  @ 869E654
	@ Castform
	cry2 Cry_Castform
	cry2 Cry_Castform
	cry2 Cry_Castform
	@ Deoxys
	cry2 Cry_Deoxys
	cry2 Cry_Deoxys
	cry2 Cry_Deoxys
	@ Parslito
	cry2_not Cry_Parslito
	cry2_not Cry_Parslito
	@ Mojisley
	cry2_not Cry_Mojisley
	cry2_not Cry_Mojisley
	@ Notyuhdad
	cry2_not Cry_Notyuhdad
	@ Choccudle
	cry2_not Cry_Choccudle
	@ Choctic
	cry2_not Cry_Choctic
	@ Rotom
	cry2_not Cry_Rotom
	cry2_not Cry_Rotom
	cry2_not Cry_Rotom
	cry2_not Cry_Rotom
	cry2_not Cry_Rotom
	@ Giratina
	cry2_not Cry_Giratina
	@ Shaymin
	cry2_not Cry_Shaymin_Sky
	@ Arceus
	cry2_not Cry_Arceus
	cry2_not Cry_Arceus
	cry2_not Cry_Arceus
	cry2_not Cry_Arceus
	cry2_not Cry_Arceus
	cry2_not Cry_Arceus
	cry2_not Cry_Arceus
	cry2_not Cry_Arceus
	cry2_not Cry_Arceus
	cry2_not Cry_Arceus
	cry2_not Cry_Arceus
	cry2_not Cry_Arceus
	cry2_not Cry_Arceus
	cry2_not Cry_Arceus
	cry2_not Cry_Arceus
	cry2_not Cry_Arceus
	cry2_not Cry_Arceus
	@ Basculin
	cry2_not Cry_Basculin
	@ Darmanitan
	cry2_not Cry_Darmanitan
	cry2_not Cry_Darmanitan
	@ Deerling
	cry2_not Cry_Deerling
	cry2_not Cry_Deerling
	cry2_not Cry_Deerling
	@ Sawsbuck
	cry2_not Cry_Sawsbuck
	cry2_not Cry_Sawsbuck
	cry2_not Cry_Sawsbuck
	@ Therian Forms
	cry2_not Cry_Tornadus_Therian
	cry2_not Cry_Thundurus_Therian
	cry2_not Cry_Landorus_Therian
	@ Kyurem
	cry2_not Cry_Kyurem_White
	cry2_not Cry_Kyurem_Black
	@ Keldeo
	cry2_not Cry_Keldeo
	@ Meloetta
	cry2_not Cry_Meloetta
	@ Genesect
	cry2_not Cry_Genesect
	cry2_not Cry_Genesect
	cry2_not Cry_Genesect
	cry2_not Cry_Genesect
	@ Greninja
	cry2_not Cry_Greninja
	cry2_not Cry_Greninja
	@ Vivillon
	cry2_not Cry_Vivillon
	cry2_not Cry_Vivillon
	cry2_not Cry_Vivillon
	cry2_not Cry_Vivillon
	cry2_not Cry_Vivillon
	cry2_not Cry_Vivillon
	cry2_not Cry_Vivillon
	cry2_not Cry_Vivillon
	cry2_not Cry_Vivillon
	cry2_not Cry_Vivillon
	cry2_not Cry_Vivillon
	cry2_not Cry_Vivillon
	cry2_not Cry_Vivillon
	cry2_not Cry_Vivillon
	cry2_not Cry_Vivillon
	cry2_not Cry_Vivillon
	cry2_not Cry_Vivillon
	cry2_not Cry_Vivillon
	cry2_not Cry_Vivillon
	@ Flabébé
	cry2_not Cry_Flabebe
	cry2_not Cry_Flabebe
	cry2_not Cry_Flabebe
	cry2_not Cry_Flabebe
	@ Floette
	cry2_not Cry_Floette
	cry2_not Cry_Floette
	cry2_not Cry_Floette
	cry2_not Cry_Floette
	cry2_not Cry_Floette_Eternal_Flower
	@ Florges
	cry2_not Cry_Florges
	cry2_not Cry_Florges
	cry2_not Cry_Florges
	cry2_not Cry_Florges
	@ Furfrou
	cry2_not Cry_Furfrou
	cry2_not Cry_Furfrou
	cry2_not Cry_Furfrou
	cry2_not Cry_Furfrou
	cry2_not Cry_Furfrou
	cry2_not Cry_Furfrou
	cry2_not Cry_Furfrou
	cry2_not Cry_Furfrou
	cry2_not Cry_Furfrou
	@ Meowstic
	cry2_not Cry_Meowstic
	@ Aegislash
	cry2_not Cry_Aegislash
	@ Pumpkaboo
	cry2_not Cry_Pumpkaboo
	cry2_not Cry_Pumpkaboo
	cry2_not Cry_Pumpkaboo_Super
	@ Gourgeist
	cry2_not Cry_Gourgeist
	cry2_not Cry_Gourgeist
	cry2_not Cry_Gourgeist_Super
	@ Xerneas
	cry2_not Cry_Xerneas
	@ Zygarde
	cry2_not Cry_Zygarde_10
	cry2_not Cry_Zygarde_10
	cry2_not Cry_Zygarde
	cry2_not Cry_Zygarde_Complete
	@ Hoopa
	cry2_not Cry_Hoopa_Unbound
	@ Oricorio
	cry2_not Cry_Oricorio_Pom_Pom
	cry2_not Cry_Oricorio_Pa_u
	cry2_not Cry_Oricorio_Sensu
	@ Rockruff
	cry2_not Cry_Rockruff
	@ Lycanroc
	cry2_not Cry_Lycanroc_Midnight
	cry2_not Cry_Lycanroc_Dusk
	@ Wishiwashi
	cry2_not Cry_Wishiwashi_School
	@ Silvally
	cry2_not Cry_Silvally
	cry2_not Cry_Silvally
	cry2_not Cry_Silvally
	cry2_not Cry_Silvally
	cry2_not Cry_Silvally
	cry2_not Cry_Silvally
	cry2_not Cry_Silvally
	cry2_not Cry_Silvally
	cry2_not Cry_Silvally
	cry2_not Cry_Silvally
	cry2_not Cry_Silvally
	cry2_not Cry_Silvally
	cry2_not Cry_Silvally
	cry2_not Cry_Silvally
	cry2_not Cry_Silvally
	cry2_not Cry_Silvally
	cry2_not Cry_Silvally
	@ Minior
	cry2_not Cry_Minior
	cry2_not Cry_Minior
	cry2_not Cry_Minior
	cry2_not Cry_Minior
	cry2_not Cry_Minior
	cry2_not Cry_Minior
	cry2_not Cry_Minior
	cry2_not Cry_Minior
	cry2_not Cry_Minior
	cry2_not Cry_Minior
	cry2_not Cry_Minior
	cry2_not Cry_Minior
	cry2_not Cry_Minior
	@ Mimikyu
	cry2_not Cry_Mimikyu
	@ Necrozma
	cry2_not Cry_Necrozma_Dusk_Mane
	cry2_not Cry_Necrozma_Dawn_Wings
	cry2_not Cry_Necrozma_Ultra
	@ Magearna
	cry2_not Cry_Magearna
		@ Cramorant
	cry2_not Cry_Cramorant
	cry2_not Cry_Cramorant
	@ Toxtricity
	cry2_not Cry_Toxtricity_Low_Key
	@ Sinistea
	cry2_not Cry_Sinistea
	@ Polteageist
	cry2_not Cry_Polteageist
	@ Alcremie
	cry2_not Cry_Alcremie
	cry2_not Cry_Alcremie
	cry2_not Cry_Alcremie
	cry2_not Cry_Alcremie
	cry2_not Cry_Alcremie
	cry2_not Cry_Alcremie
	cry2_not Cry_Alcremie
	cry2_not Cry_Alcremie
	@ Eiscue
	cry2_not Cry_Eiscue_Noice_Face
	@ Indeedee
	cry2_not Cry_Indeedee_Female
	@ Morpeko
	cry2_not Cry_Morpeko_Hangry
	@ Zacian
	cry2_not Cry_Zacian_Crowned_Sword
	@ Zamazenta
	cry2_not Cry_Zamazenta_Crowned_Shield
	@ Eternatus
	cry2_not Cry_Eternatus_Eternamax
	@ Urshifu
	cry2_not Cry_Urshifu_Rapid_Strike_Style
	@ Zarude
	cry2_not Cry_Zarude
	@ Calyrex
	cry2_not Cry_Calyrex_Ice_Rider
	cry2_not Cry_Calyrex_Shadow_Rider
