#if GAME_LANGUAGE == LANGUAGE_SPANISH
gText_WantToUseSurf:: @ 8272FD6
	.string "El agua tiene buena pinta…\n¿Quieres hacer Surf?$"

Text_GigalphaSurf:: @ 8272FD6
	.string "El agua tiene buena pinta…\n¿Llamas al Gigalpha de Papá?$"

gText_PlayerUsedSurf:: @ 827300D
	.string "¡{STR_VAR_1} usó Surf!$"
#else
gText_WantToUseSurf:: @ 8272FD6
	.string "The water is dyed a deep blue…\nWould you like to Surf?$"

Text_GigalphaSurf:: @ 8272FD6
	.string "The water is dyed a deep blue…\nCall Poke Ride's Jebony to Surf?$"

gText_PlayerUsedSurf:: @ 827300D
	.string "{STR_VAR_1} used Surf!$"
#endif
